from lib import *

FRIEND_CHAT_PACKET_TYPE_LIST = {

    "FRIEND_CHAT_REGISTER"                           : 1,
    "FRIEND_CHAT_UNREGISTER"                         : 2,
    "FRIEND_CHAT_REGISTER_CONFIRMATION"              : 3,
    "FRIEND_CHAT_IDLE"                               : 4,
    "FRIEND_CHAT_TYPING"                             : 5,
    "FRIEND_CHAT_MSG"                                : 6,
    "FRIEND_CHAT_MSG_EDIT"                           : 7,
    "FRIEND_CHAT_BROKEN_MSG"                         : 8,
    "FRIEND_CHAT_BROKEN_MSG_EDIT"                    : 9,
    "FRIEND_CHAT_MULTIPLE_MSG"                       : 10,
    "FRIEND_CHAT_DELIVERED"                          : 15,
    "FRIEND_CHAT_SENT"                               : 16,
    "FRIEND_CHAT_SEEN"                               : 17,
    "FRIEND_CHAT_SEEN_CONFIRMATION"                  : 18,
    "FRIEND_CHAT_MULTIPLE_MSG_DELETE"                : 19,
    "FRIEND_CHAT_MSG_DELETE_CONFIRMATION"            : 20,
    "FRIEND_CHAT_BROKEN"                             : 24,
    "FRIEND_CHAT_BROKEN_CONFIRMATION"                : 25,
    "FRIEND_CHAT_BLOCK"                              : 27,
    "FRIEND_CHAT_UNBLOCK"                            : 28,
    "FRIEND_CHAT_BLOCK_UNBLOCK_CONFIRMATION"         : 29

}

FRIEND_CHAT_PACKET_TYPE = obj(FRIEND_CHAT_PACKET_TYPE_LIST)


TAG_CHAT_PACKET_TYPE_LIST = {

    "TAG_CHAT_TAG_REGISTER"                          : 41,
    "TAG_CHAT_TAG_UNREGISTER"                        : 42,
    "TAG_CHAT_TAG_REGISTER_CONFIRMATION"             : 43,
    "TAG_CHAT_TAG_INFORMATION"                       : 46,
    "TAG_CHAT_TAG_INFORMATION_CONFIRMATION"          : 47,
    "TAG_CHAT_TAG_MEMBER_ADD"                        : 51,
    "TAG_CHAT_TAG_MEMBER_ADD_CONFIRMATION"           : 52,
    "TAG_CHAT_MEMBER_REMOVE_LEAVE"                   : 53,
    "TAG_CHAT_MEMBER_REMOVE_LEAVE_CONFIRMATION"      : 54,
    "TAG_CHAT_TAG_MEMBER_TYPE_CHANGE"                : 55,
    "TAG_CHAT_TAG_MEMBER_TYPE_CHANGE_CONFIRMATION"   : 56,
    "TAG_CHAT_IDLE"                                  : 61,
    "TAG_CHAT_TYPING"                                : 62,
    "TAG_CHAT_MSG"                                   : 63,
    "TAG_CHAT_MSG_EDIT"                              : 64,
    "TAG_CHAT_BROKEN_MSG"                            : 65,
    "TAG_CHAT_BROKEN_MSG_EDIT"                       : 66,
    "TAG_CHAT_MULTIPLE_MSG"                          : 67,
    "TAG_CHAT_DELIVERED"                             : 68,
    "TAG_CHAT_SENT"                                  : 69,
    "TAG_CHAT_SEEN"                                  : 70,
    "TAG_CHAT_SEEN_CONFIRMATION"                     : 71,
    "TAG_CHAT_MULTIPLE_MSG_DELETE"                   : 72,
    "TAG_CHAT_MSG_DELETE_CONFIRMATION"               : 73,
    "TAG_CHAT_GENERAL_BROKEN_PACKET"                 : 74,
    "TAG_CHAT_GENERAL_BROKEN_PACKET_CONFIRMATION"    : 75

}

TAG_CHAT_PACKET_TYPE = obj(TAG_CHAT_PACKET_TYPE_LIST)

OFFLINE_PACKET_TYPE_LIST = {
    "OFFLINE_FRIEND_INFORMATION"                     : 91,
    "OFFLINE_FRIEND_INFORMATION_CONFIRMATION"        : 92,
    "OFFLINE_GET_REQUEST"                            : 93,
    "OFFLINE_GET_REQUEST_CONFIRMATION"               : 94,
    "OFFLINE_FRIEND_UNREAD_MESSAGE"                  : 95,
    "OFFLINE_FRIEND_UNREAD_MESSAGE_CONFIRMATION"     : 96,
    "OFFLINE_FRIEND_HISTORY_MESSAGE_REQUEST"         : 97,
    "OFFLINE_FRIEND_HISTORY_MESSAGE"                 : 98,
    "OFFLINE_FRIEND_HISTORY_MESSAGE_CONFIRMATION"    : 99,
    "OFFLINE_GET_FRIEND_MESSAGE_STATUS"              : 100,
    "OFFLINE_GET_FRIEND_MESSAGE_STATUS_CONFIRMATION" : 101,
    "OFFLINE_TAG_INFORMATION_ACTIVITY"               : 104,
    "OFFLINE_MY_TAG_LIST"                            : 105,
    "OFFLINE_TAG_UNREAD_MESSAGE"                     : 106,
    "OFFLINE_TAG_UNREAD_MESSAGE_CONFIRMATION"        : 107,
    "OFFLINE_TAG_CREATE_TAG"                         : 108,
    "OFFLINE_TAG_CREATE_TAG_CONFIRMATION"            : 109,
    "OFFLINE_TAG_HISTORY_MESSAGE_REQUEST"            : 110,
    "OFFLINE_TAG_HISTORY_MESSAGE"                    : 111,
    "OFFLINE_GET_TAG_INFORMATION_WITH_MEMBERS"       : 112,
    "OFFLINE_TAG_INFORMATION_WITH_MEMBERS"           : 113,
    "OFFLINE_TAG_CONFIRMATION"                       : 117,
    "OFFLINE_BROKEN_HISTORY_PACKET"                  : 118,
    "OFFLINE_BROKEN_PACKET"                          : 119,
    "OFFLINE_BROKEN_PACKET_CONFIRMATION"             : 120
}

OFFLINE_PACKET_TYPE =obj(OFFLINE_PACKET_TYPE_LIST)

PACKET_TYPE_NAME_MAP = {}

ALL_PACKET_TYPE_LIST = [ FRIEND_CHAT_PACKET_TYPE_LIST, TAG_CHAT_PACKET_TYPE_LIST, OFFLINE_PACKET_TYPE_LIST ]
for a_packet_type_list in ALL_PACKET_TYPE_LIST:
	for a_packet_name, a_packet_type_value in a_packet_type_list.iteritems():
		PACKET_TYPE_NAME_MAP[a_packet_type_value] = a_packet_name


CONSTANTS = {
	"ATTRIBUTE_TYPE" : {
		"INTEGER" 	: 1, 
		"STRING" 	: 2, 
		"BYTE" 		: 3 
	}	
}

CONSTANTS['ATTRIBUTE_TYPE_VALUE'] = {}
for attr_type, value in CONSTANTS['ATTRIBUTE_TYPE'].iteritems():
    CONSTANTS['ATTRIBUTE_TYPE_VALUE'][value] = attr_type


PACKET_ATTRIBUTE_OBJECT = {
    "PACKET_TYPE":                       1,
    "USER_ID":                           2,
    "FRIEND_ID":                         3,
    "PACKET_ID_LENGTH":                  4,
    "PACKET_ID":                         5,
    "PLATFORM":                          6,
    "CHAT_BINDING_PORT":                 7,
    "TAG_ID":                            8,
    "ONLINE_STATUS":                     9,
    "USER_MOOD":                         10,
    "MESSAGE_TYPE":                      11,
    "TIMEOUT":                           12,
    "LATITUDE":                          13,
    "LONGITUDE":                         14,
    "MESSAGE_LENGTH":                    15,
    "MESSAGE":                           16,
    "MESSAGE_DATE":                      17,
    "NO_OF_MESSAGE":                     18,
    "FULL_NAME_LENGTH":                  19,
    "FULL_NAME":                         20,
    "NO_OF_PACKET":                      21,
    "SEQUENCE_NO":                       22,
    "NO_OF_MEMBERS":                     23,
    "UPDATE_TIME":                       24,
    "SERVER_DATE":                       25,
    "LAST_ONLINE_TIME":                  26,
    "NO_OF_ITEMS":                       27,
    "BLOCK_UNBLOCK_DATE":                28,
    "MESSAGE_STATUS":                    29,
    "IS_ADD_TO_DB":                      30,
    "TAG_NAME_LENGTH":                   31,
    "TAG_NAME":                          32,
    "TAG_PICTURE_URL_LENGTH":            33,
    "TAG_PICTURE_URL":                   34,
    "TAG_MEMBER_TYPE":                   35,
    "TAG_MEMBER_ADDED_BY":               36,
    "TAG_NO_OF_MEMBERS":                 37,
    "TAG_NO_OF_BROKEN_PKT":              38,
    "TAG_INFORMATION_UPDATE_FLAG":       39,
    "TAG_INFORMATION_TAG_NO_OF_MEMBERS": 40,
    "REGISTRATION_TYPE":                 41,
    "PAGE_DIRECTION":                    42,
    "PAGE_LIMIT":                        43,
    "ACTIVITY_TYPE":                     45,
    "ACTIVITY_VALUE_LENGTH":             46,
    "ACTIVITY_VALUE":                    47,
    "CHANGED_BY_USER_ID":                48,
    "FRIEND_APP_TYPE":                   60,
    "FRIEND_DEVICE_TOKEN_LENGTH":        61,
    "FRIEND_DEVICE_TOKEN":               62,
    "IS_SECRET_VISIBLE":                 63,
    "APP_VERSION":                       64,
    "RAW_DATA_BYTE":                     80

}

PACKET_ATTRIBUTE = obj(PACKET_ATTRIBUTE_OBJECT)

PACKET_ATTRIBUTE_NAME_MAP = {}
for an_attribute_name, an_attribute_value in PACKET_ATTRIBUTE_OBJECT.iteritems():
    PACKET_ATTRIBUTE_NAME_MAP[an_attribute_value] = an_attribute_name


PACKET_ATTRIBUTE_INFO = {}

#1
PACKET_ATTRIBUTE_INFO[PACKET_ATTRIBUTE.PACKET_TYPE] = {
    "VAR_TYPE" :  CONSTANTS["ATTRIBUTE_TYPE"]["INTEGER"],
    "SIZE" : 1
}

#2
PACKET_ATTRIBUTE_INFO[PACKET_ATTRIBUTE.USER_ID] = {
    "VAR_TYPE" :  CONSTANTS["ATTRIBUTE_TYPE"]["INTEGER"],
    "SIZE" : 8
}

#3
PACKET_ATTRIBUTE_INFO[PACKET_ATTRIBUTE.FRIEND_ID] = {
    "VAR_TYPE" :  CONSTANTS["ATTRIBUTE_TYPE"]["INTEGER"],
    "SIZE" : 8
}

#4
PACKET_ATTRIBUTE_INFO[PACKET_ATTRIBUTE.PACKET_ID_LENGTH] = {
    "VAR_TYPE" :  CONSTANTS["ATTRIBUTE_TYPE"]["INTEGER"],
    "SIZE" : 1
}

#5
PACKET_ATTRIBUTE_INFO[PACKET_ATTRIBUTE.PACKET_ID] = {
    "VAR_TYPE" :  CONSTANTS["ATTRIBUTE_TYPE"]["STRING"],
    "SIZE" : -1 
}

#6
PACKET_ATTRIBUTE_INFO[PACKET_ATTRIBUTE.PLATFORM] = {
    "VAR_TYPE" :  CONSTANTS["ATTRIBUTE_TYPE"]["INTEGER"],
    "SIZE" :  1
}

#7
PACKET_ATTRIBUTE_INFO[PACKET_ATTRIBUTE.CHAT_BINDING_PORT] = {
    "VAR_TYPE" :  CONSTANTS["ATTRIBUTE_TYPE"]["INTEGER"],
    "SIZE" :  4
}

#8
PACKET_ATTRIBUTE_INFO[PACKET_ATTRIBUTE.TAG_ID] = {
    "VAR_TYPE" :  CONSTANTS["ATTRIBUTE_TYPE"]["INTEGER"],
    "SIZE" :  8
}

#9
PACKET_ATTRIBUTE_INFO[PACKET_ATTRIBUTE.ONLINE_STATUS] = {
    "VAR_TYPE" :  CONSTANTS["ATTRIBUTE_TYPE"]["INTEGER"],
    "SIZE" :  1
}

#10
PACKET_ATTRIBUTE_INFO[PACKET_ATTRIBUTE.USER_MOOD] = {
    "VAR_TYPE" :  CONSTANTS["ATTRIBUTE_TYPE"]["INTEGER"],
    "SIZE" :  1
}

#11
PACKET_ATTRIBUTE_INFO[PACKET_ATTRIBUTE.MESSAGE_TYPE] = {
    "VAR_TYPE" :  CONSTANTS["ATTRIBUTE_TYPE"]["INTEGER"],
    "SIZE" :  1
}

#12
PACKET_ATTRIBUTE_INFO[PACKET_ATTRIBUTE.TIMEOUT] = {
    "VAR_TYPE" :  CONSTANTS["ATTRIBUTE_TYPE"]["INTEGER"],
    "SIZE" :  2
}

#13
PACKET_ATTRIBUTE_INFO[PACKET_ATTRIBUTE.LATITUDE] = {
    "VAR_TYPE" :  CONSTANTS["ATTRIBUTE_TYPE"]["INTEGER"],
    "SIZE" :  4
}

#14
PACKET_ATTRIBUTE_INFO[PACKET_ATTRIBUTE.LONGITUDE] = {
    "VAR_TYPE" :  CONSTANTS["ATTRIBUTE_TYPE"]["INTEGER"],
    "SIZE" :  4
}

#15
PACKET_ATTRIBUTE_INFO[PACKET_ATTRIBUTE.MESSAGE_LENGTH] = {
    "VAR_TYPE" :  CONSTANTS["ATTRIBUTE_TYPE"]["INTEGER"],
    "SIZE" :  2
}

#16
PACKET_ATTRIBUTE_INFO[PACKET_ATTRIBUTE.MESSAGE] = {
    "VAR_TYPE" :  CONSTANTS["ATTRIBUTE_TYPE"]["STRING"],
    "SIZE" :  -1
}

#17
PACKET_ATTRIBUTE_INFO[PACKET_ATTRIBUTE.MESSAGE_DATE] = {
    "VAR_TYPE" :  CONSTANTS["ATTRIBUTE_TYPE"]["INTEGER"],
    "SIZE" :  8
}

#18
PACKET_ATTRIBUTE_INFO[PACKET_ATTRIBUTE.NO_OF_MESSAGE] = {
    "VAR_NAME" : 'messagesLength',
    "VAR_TYPE" :  CONSTANTS["ATTRIBUTE_TYPE"]["INTEGER"],
    "VAR_CONTAINER_NAME" : 'messages',
    "SIZE" :  1
}

#19
PACKET_ATTRIBUTE_INFO[PACKET_ATTRIBUTE.FULL_NAME_LENGTH] = {
    "VAR_TYPE" :  CONSTANTS["ATTRIBUTE_TYPE"]["INTEGER"],
    "SIZE" :  1
}

#20
PACKET_ATTRIBUTE_INFO[PACKET_ATTRIBUTE.FULL_NAME] = {
    "VAR_TYPE" :  CONSTANTS["ATTRIBUTE_TYPE"]["STRING"],
    "SIZE" :  -1
}

#21
PACKET_ATTRIBUTE_INFO[PACKET_ATTRIBUTE.NO_OF_PACKET] = {
    "VAR_NAME" : 'packetsLength',
    "VAR_TYPE" :  CONSTANTS["ATTRIBUTE_TYPE"]["INTEGER"],
    "VAR_CONTAINER_NAME" : 'packets',
    "SIZE" :  1
}

#22
PACKET_ATTRIBUTE_INFO[PACKET_ATTRIBUTE.SEQUENCE_NO] = {
    "VAR_NAME" : 'sequenceNo',
    "VAR_TYPE" :  CONSTANTS["ATTRIBUTE_TYPE"]["INTEGER"],
    "SIZE" :  1
}

#23
PACKET_ATTRIBUTE_INFO[PACKET_ATTRIBUTE.NO_OF_MEMBERS] = {
    "VAR_NAME" : 'membersLength',
    "VAR_TYPE" :  CONSTANTS["ATTRIBUTE_TYPE"]["INTEGER"],
    "VAR_CONTAINER_NAME" : 'members',
    "SIZE" :  2
}

#24
PACKET_ATTRIBUTE_INFO[PACKET_ATTRIBUTE.UPDATE_TIME] = {
    "VAR_TYPE" :  CONSTANTS["ATTRIBUTE_TYPE"]["INTEGER"],
    "SIZE" :  8
}

#25
PACKET_ATTRIBUTE_INFO[PACKET_ATTRIBUTE.SERVER_DATE] = {
    "VAR_TYPE" :  CONSTANTS["ATTRIBUTE_TYPE"]["INTEGER"],
    "SIZE" :  8
}

#26
PACKET_ATTRIBUTE_INFO[PACKET_ATTRIBUTE.LAST_ONLINE_TIME] = {
    "VAR_TYPE" :  CONSTANTS["ATTRIBUTE_TYPE"]["INTEGER"],
    "SIZE" :  8
}

#27
PACKET_ATTRIBUTE_INFO[PACKET_ATTRIBUTE.NO_OF_ITEMS] = {
    "VAR_TYPE" :  CONSTANTS["ATTRIBUTE_TYPE"]["INTEGER"],
    "VAR_CONTAINER_NAME" : 'items',
    "SIZE" :  2
}

#28
PACKET_ATTRIBUTE_INFO[PACKET_ATTRIBUTE.BLOCK_UNBLOCK_DATE] = {
    "VAR_NAME" : 'blockUnblockDate',
    "VAR_TYPE" :  CONSTANTS["ATTRIBUTE_TYPE"]["INTEGER"],
    "SIZE" :  8
}

#29
PACKET_ATTRIBUTE_INFO[PACKET_ATTRIBUTE.MESSAGE_STATUS] = {
    "VAR_NAME" : 'status',
    "VAR_TYPE" :  CONSTANTS["ATTRIBUTE_TYPE"]["INTEGER"],
    "SIZE" :  1
}

#30
PACKET_ATTRIBUTE_INFO[PACKET_ATTRIBUTE.IS_ADD_TO_DB] = {
    "VAR_TYPE" :  CONSTANTS["ATTRIBUTE_TYPE"]["INTEGER"],
    "SIZE" :  1
}


#31
PACKET_ATTRIBUTE_INFO[PACKET_ATTRIBUTE.TAG_NAME_LENGTH] = {
    "VAR_TYPE" :  CONSTANTS["ATTRIBUTE_TYPE"]["INTEGER"],
    "SIZE" :  2
}

#32
PACKET_ATTRIBUTE_INFO[PACKET_ATTRIBUTE.TAG_NAME] = {
    "VAR_TYPE" :  CONSTANTS["ATTRIBUTE_TYPE"]["STRING"],
    "SIZE" :  -1
}

#33
PACKET_ATTRIBUTE_INFO[PACKET_ATTRIBUTE.TAG_PICTURE_URL_LENGTH] = {
    "VAR_NAME" : 'tagPictureUrlLength',
    "VAR_TYPE" :  CONSTANTS["ATTRIBUTE_TYPE"]["INTEGER"],
    "SIZE" :  1
}

#34
PACKET_ATTRIBUTE_INFO[PACKET_ATTRIBUTE.TAG_PICTURE_URL] = {
    "VAR_TYPE" :  CONSTANTS["ATTRIBUTE_TYPE"]["STRING"],
    "SIZE" :  -1
}

#35
PACKET_ATTRIBUTE_INFO[PACKET_ATTRIBUTE.TAG_MEMBER_TYPE] = {
    "VAR_NAME" : 'status',
    "VAR_TYPE" :  CONSTANTS["ATTRIBUTE_TYPE"]["INTEGER"],
    "SIZE" :  1
}

#36
PACKET_ATTRIBUTE_INFO[PACKET_ATTRIBUTE.TAG_MEMBER_ADDED_BY] = {
    "VAR_NAME" : 'addedBy',
    "VAR_TYPE" :  CONSTANTS["ATTRIBUTE_TYPE"]["INTEGER"],
    "SIZE" :  8
}

#37
PACKET_ATTRIBUTE_INFO[PACKET_ATTRIBUTE.TAG_NO_OF_MEMBERS] = {
    "VAR_NAME" : 'tagMembersLength',
    "VAR_TYPE" :  CONSTANTS["ATTRIBUTE_TYPE"]["INTEGER"],
    "VAR_CONTAINER_NAME" : 'tagMembers',
    "SIZE" :  2
}

#38
PACKET_ATTRIBUTE_INFO[PACKET_ATTRIBUTE.TAG_NO_OF_BROKEN_PKT] = {
    "VAR_NAME" : 'brokenPacketsLength',
    "VAR_TYPE" :  CONSTANTS["ATTRIBUTE_TYPE"]["INTEGER"],
    "VAR_CONTAINER_NAME" : 'brokenPackets',
    "SIZE" :  1
}

#39
PACKET_ATTRIBUTE_INFO[PACKET_ATTRIBUTE.TAG_INFORMATION_UPDATE_FLAG] = {
    "VAR_NAME" : 'updateFlag',
    "VAR_TYPE" :  CONSTANTS["ATTRIBUTE_TYPE"]["INTEGER"],
    "SIZE" :  1
}

#40
PACKET_ATTRIBUTE_INFO[PACKET_ATTRIBUTE.TAG_INFORMATION_TAG_NO_OF_MEMBERS] = {    
    "VAR_NAME" : 'tagMembersCount',
    "VAR_TYPE" :  CONSTANTS["ATTRIBUTE_TYPE"]["INTEGER"],
    "SIZE" :  2
}

41
PACKET_ATTRIBUTE_INFO[PACKET_ATTRIBUTE.REGISTRATION_TYPE] = {    
    "VAR_NAME" : 'registrationType',
    "VAR_TYPE" :  CONSTANTS["ATTRIBUTE_TYPE"]["INTEGER"],
    "SIZE" :  1
}

42
PACKET_ATTRIBUTE_INFO[PACKET_ATTRIBUTE.PAGE_DIRECTION] = {    
    "VAR_NAME" : 'pageDirection',
    "VAR_TYPE" :  CONSTANTS["ATTRIBUTE_TYPE"]["INTEGER"],
    "SIZE" :  1
}

43
PACKET_ATTRIBUTE_INFO[PACKET_ATTRIBUTE.PAGE_LIMIT] = {    
    "VAR_NAME" : 'pageLimit',
    "VAR_TYPE" :  CONSTANTS["ATTRIBUTE_TYPE"]["INTEGER"],
    "SIZE" :  1
}

#45
PACKET_ATTRIBUTE_INFO[PACKET_ATTRIBUTE.ACTIVITY_TYPE] = {    
    "VAR_TYPE" :  CONSTANTS["ATTRIBUTE_TYPE"]["INTEGER"],
    "CONDITIONAL" : True,
    "SIZE" :  1
}

#46
PACKET_ATTRIBUTE_INFO[PACKET_ATTRIBUTE.ACTIVITY_VALUE_LENGTH] = {    
    "VAR_TYPE" :  CONSTANTS["ATTRIBUTE_TYPE"]["INTEGER"],
    "SIZE" :  2
}

#47
PACKET_ATTRIBUTE_INFO[PACKET_ATTRIBUTE.ACTIVITY_VALUE] = {    
    "VAR_TYPE" :  CONSTANTS["ATTRIBUTE_TYPE"]["STRING"],
    "SIZE" :  -1
}

#48
PACKET_ATTRIBUTE_INFO[PACKET_ATTRIBUTE.CHANGED_BY_USER_ID] = {    
    "VAR_TYPE" :  CONSTANTS["ATTRIBUTE_TYPE"]["INTEGER"],
    "SIZE" :  8
}


#60
PACKET_ATTRIBUTE_INFO[PACKET_ATTRIBUTE.FRIEND_APP_TYPE] = {    
    "VAR_TYPE" :  CONSTANTS["ATTRIBUTE_TYPE"]["INTEGER"],
    "SIZE" :  1
}

#61
PACKET_ATTRIBUTE_INFO[PACKET_ATTRIBUTE.FRIEND_DEVICE_TOKEN_LENGTH] = {    
    "VAR_TYPE" :  CONSTANTS["ATTRIBUTE_TYPE"]["INTEGER"],
    "SIZE" :  2
}

#62
PACKET_ATTRIBUTE_INFO[PACKET_ATTRIBUTE.FRIEND_DEVICE_TOKEN] = {    
    "VAR_TYPE" :  CONSTANTS["ATTRIBUTE_TYPE"]["STRING"],
    "SIZE" :  -1
}

#63
PACKET_ATTRIBUTE_INFO[PACKET_ATTRIBUTE.IS_SECRET_VISIBLE] = {    
    "VAR_TYPE" :  CONSTANTS["ATTRIBUTE_TYPE"]["INTEGER"],
    "SIZE" :  1
}


#64
PACKET_ATTRIBUTE_INFO[PACKET_ATTRIBUTE.APP_VERSION] = {    
    "VAR_TYPE" :  CONSTANTS["ATTRIBUTE_TYPE"]["INTEGER"],
    "SIZE" :  2
}


#80
PACKET_ATTRIBUTE_INFO[PACKET_ATTRIBUTE.RAW_DATA_BYTE] = {    
    "VAR_TYPE" :  CONSTANTS["ATTRIBUTE_TYPE"]["BYTE"],
    "VAR_NAME" : 'bytes',
    "SIZE" :  -2
}


PACKET_INFO  = {}

##1
PACKET_INFO[ FRIEND_CHAT_PACKET_TYPE.FRIEND_CHAT_REGISTER ] = \
{

    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.USER_ID,
        PACKET_ATTRIBUTE.FRIEND_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID,
        PACKET_ATTRIBUTE.PLATFORM

    ],
    "CONFIRMATION" : True,
    "BROKEN" : False,
    #1, 2, 3, 4, 5, 6
}

##2
PACKET_INFO[ FRIEND_CHAT_PACKET_TYPE.FRIEND_CHAT_UNREGISTER ] = \
{

    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.USER_ID,
        PACKET_ATTRIBUTE.FRIEND_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID,
        PACKET_ATTRIBUTE.PLATFORM,
        PACKET_ATTRIBUTE.ONLINE_STATUS,
        PACKET_ATTRIBUTE.USER_MOOD
    ],
    "CONFIRMATION" : False,
    "BROKEN" : False,

    #1, 2, 3, 4, 5, 6
}


##3
PACKET_INFO[ FRIEND_CHAT_PACKET_TYPE.FRIEND_CHAT_REGISTER_CONFIRMATION ] = \
{

    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.FRIEND_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID,
        PACKET_ATTRIBUTE.CHAT_BINDING_PORT,
        PACKET_ATTRIBUTE.SERVER_DATE
    ],
	"CONFIRMATION" : False,
    "BROKEN" : False,
    #1, 3, 4, 5, ...
}

##4
PACKET_INFO[ FRIEND_CHAT_PACKET_TYPE.FRIEND_CHAT_IDLE ] = \
{

    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.USER_ID,
        PACKET_ATTRIBUTE.FRIEND_ID,
        PACKET_ATTRIBUTE.PLATFORM,
    ],
    "CONFIRMATION" : False,
    "BROKEN" : False,
}

##5
PACKET_INFO[ FRIEND_CHAT_PACKET_TYPE.FRIEND_CHAT_TYPING ] = \
{

    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.USER_ID,
        PACKET_ATTRIBUTE.FRIEND_ID,
        PACKET_ATTRIBUTE.PLATFORM,
    ],
    "CONFIRMATION" : False,
    "BROKEN" : False,
} 

##6
PACKET_INFO[ FRIEND_CHAT_PACKET_TYPE.FRIEND_CHAT_MSG ] = \
{
    "BROKEN_CONTAINER" : 'message',
    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.USER_ID,
        PACKET_ATTRIBUTE.FRIEND_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID,
        PACKET_ATTRIBUTE.MESSAGE_TYPE,
        PACKET_ATTRIBUTE.TIMEOUT,
        PACKET_ATTRIBUTE.MESSAGE_LENGTH,
        PACKET_ATTRIBUTE.MESSAGE,
        PACKET_ATTRIBUTE.MESSAGE_DATE,
        PACKET_ATTRIBUTE.IS_SECRET_VISIBLE,
        PACKET_ATTRIBUTE.PLATFORM,
    ],
    "CONFIRMATION" : True,
    "BROKEN" : True,

}

##7
PACKET_INFO[ FRIEND_CHAT_PACKET_TYPE.FRIEND_CHAT_MSG_EDIT ] = \
{

    "BROKEN_CONTAINER" : 'message',
    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.USER_ID,
        PACKET_ATTRIBUTE.FRIEND_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID,
        PACKET_ATTRIBUTE.MESSAGE_TYPE,
        PACKET_ATTRIBUTE.TIMEOUT,
        PACKET_ATTRIBUTE.MESSAGE_LENGTH,
        PACKET_ATTRIBUTE.MESSAGE,
        PACKET_ATTRIBUTE.MESSAGE_DATE,
        PACKET_ATTRIBUTE.IS_SECRET_VISIBLE,
        PACKET_ATTRIBUTE.PLATFORM

    ],
    "CONFIRMATION" : True,
    "BROKEN" : True,
}

##8
PACKET_INFO[ FRIEND_CHAT_PACKET_TYPE.FRIEND_CHAT_BROKEN_MSG ] = \
{
    "BROKEN_CONTAINER" : 'message',
    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.USER_ID,
        PACKET_ATTRIBUTE.FRIEND_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID,
        PACKET_ATTRIBUTE.NO_OF_PACKET,
        PACKET_ATTRIBUTE.SEQUENCE_NO,
        PACKET_ATTRIBUTE.MESSAGE_TYPE,
        PACKET_ATTRIBUTE.TIMEOUT,
        PACKET_ATTRIBUTE.MESSAGE_LENGTH,
        PACKET_ATTRIBUTE.MESSAGE,
        PACKET_ATTRIBUTE.MESSAGE_DATE,
        PACKET_ATTRIBUTE.IS_SECRET_VISIBLE,
        PACKET_ATTRIBUTE.PLATFORM,

    ],
    "CONFIRMATION" : True,
    "BROKEN" : False,
}

##9
PACKET_INFO[ FRIEND_CHAT_PACKET_TYPE.FRIEND_CHAT_BROKEN_MSG_EDIT ] = \
{
    "BROKEN_CONTAINER" : 'message',
    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.USER_ID,
        PACKET_ATTRIBUTE.FRIEND_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID,
        PACKET_ATTRIBUTE.NO_OF_PACKET,
        PACKET_ATTRIBUTE.SEQUENCE_NO,
        PACKET_ATTRIBUTE.MESSAGE_TYPE,
        PACKET_ATTRIBUTE.TIMEOUT,
        PACKET_ATTRIBUTE.MESSAGE_LENGTH,
        PACKET_ATTRIBUTE.MESSAGE,
        PACKET_ATTRIBUTE.MESSAGE_DATE,
        PACKET_ATTRIBUTE.IS_SECRET_VISIBLE,
        PACKET_ATTRIBUTE.PLATFORM,

    ],
    "CONFIRMATION" : True,
    "BROKEN" : False,

}

##10
PACKET_INFO[ FRIEND_CHAT_PACKET_TYPE.FRIEND_CHAT_MULTIPLE_MSG ] = \
{

    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.USER_ID,
        PACKET_ATTRIBUTE.FRIEND_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID,
        PACKET_ATTRIBUTE.NO_OF_MESSAGE,
        [
            PACKET_ATTRIBUTE.PACKET_TYPE,
            PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            PACKET_ATTRIBUTE.PACKET_ID,
            PACKET_ATTRIBUTE.MESSAGE_TYPE,
            PACKET_ATTRIBUTE.TIMEOUT,
            PACKET_ATTRIBUTE.MESSAGE_LENGTH,
            PACKET_ATTRIBUTE.MESSAGE,
            PACKET_ATTRIBUTE.MESSAGE_DATE,
            PACKET_ATTRIBUTE.IS_SECRET_VISIBLE
        ]

    ],
    "CONFIRMATION" : True,
    "BROKEN" : False,    

}

##15
PACKET_INFO[ FRIEND_CHAT_PACKET_TYPE.FRIEND_CHAT_DELIVERED ] = \
{

    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.USER_ID,
        PACKET_ATTRIBUTE.FRIEND_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID,
        PACKET_ATTRIBUTE.PLATFORM
    ],
    "CONFIRMATION" : False,
    "BROKEN" : False,
    
}

##16
PACKET_INFO[ FRIEND_CHAT_PACKET_TYPE.FRIEND_CHAT_SENT ] = \
{

    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.USER_ID,
        PACKET_ATTRIBUTE.FRIEND_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID
    ],
    "CONFIRMATION" : True,
    "BROKEN" : False,
}


##17
PACKET_INFO[ FRIEND_CHAT_PACKET_TYPE.FRIEND_CHAT_SEEN ] = \
{
    "BROKEN_CONTAINER" : 'messages',
    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.USER_ID,
        PACKET_ATTRIBUTE.FRIEND_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID,
        PACKET_ATTRIBUTE.NO_OF_MESSAGE,
        [
            PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            PACKET_ATTRIBUTE.PACKET_ID,
            PACKET_ATTRIBUTE.MESSAGE_DATE,
            PACKET_ATTRIBUTE.MESSAGE_STATUS
        ],
        PACKET_ATTRIBUTE.PLATFORM
    ],
    "CONFIRMATION" : True,
    "BROKEN" : True,
}

##18
PACKET_INFO[ FRIEND_CHAT_PACKET_TYPE.FRIEND_CHAT_SEEN_CONFIRMATION ] = \
{

    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.USER_ID,
        PACKET_ATTRIBUTE.FRIEND_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID
    ],
    "CONFIRMATION" : False,
    "BROKEN" : False,
}

##19
PACKET_INFO[ FRIEND_CHAT_PACKET_TYPE.FRIEND_CHAT_MULTIPLE_MSG_DELETE ] = \
{

    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.USER_ID,
        PACKET_ATTRIBUTE.FRIEND_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID,
        PACKET_ATTRIBUTE.NO_OF_PACKET,
        [
        	PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        	PACKET_ATTRIBUTE.PACKET_ID,

        ]
    ],
    "CONFIRMATION" : True,
    "BROKEN" : False,    
}

##20
PACKET_INFO[ FRIEND_CHAT_PACKET_TYPE.FRIEND_CHAT_MSG_DELETE_CONFIRMATION ] = \
{

    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.USER_ID,
        PACKET_ATTRIBUTE.FRIEND_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID
    ],
    "CONFIRMATION" : False,
    "BROKEN" : False,  
}


##24
PACKET_INFO[ FRIEND_CHAT_PACKET_TYPE.FRIEND_CHAT_BROKEN] = \
{

    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.USER_ID,
        PACKET_ATTRIBUTE.FRIEND_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID,
        PACKET_ATTRIBUTE.NO_OF_PACKET,
        PACKET_ATTRIBUTE.SEQUENCE_NO,
        PACKET_ATTRIBUTE.RAW_DATA_BYTE


    ],
    "CONFIRMATION" : True,
    "BROKEN" : False,  
}

##25
PACKET_INFO[ FRIEND_CHAT_PACKET_TYPE.FRIEND_CHAT_BROKEN_CONFIRMATION] = \
{

    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.USER_ID,
        PACKET_ATTRIBUTE.FRIEND_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID,
        PACKET_ATTRIBUTE.SEQUENCE_NO
    ],
    "CONFIRMATION" : False,
    "BROKEN" : False,  
}

##27
PACKET_INFO[ FRIEND_CHAT_PACKET_TYPE.FRIEND_CHAT_BLOCK] = \
{

    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.USER_ID,
        PACKET_ATTRIBUTE.FRIEND_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID,
        PACKET_ATTRIBUTE.BLOCK_UNBLOCK_DATE,
        PACKET_ATTRIBUTE.IS_ADD_TO_DB


    ],
    "CONFIRMATION" : True,
    "BROKEN" : False,
}

##28
PACKET_INFO[ FRIEND_CHAT_PACKET_TYPE.FRIEND_CHAT_UNBLOCK] = \
{

    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.USER_ID,
        PACKET_ATTRIBUTE.FRIEND_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID,
        PACKET_ATTRIBUTE.BLOCK_UNBLOCK_DATE
    ],
    "CONFIRMATION" : True,
    "BROKEN" : False,
}


##29
PACKET_INFO[ FRIEND_CHAT_PACKET_TYPE.FRIEND_CHAT_BLOCK_UNBLOCK_CONFIRMATION] = \
{

    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.USER_ID,
        PACKET_ATTRIBUTE.FRIEND_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID
    ],
    "CONFIRMATION" : True,
    "BROKEN" : False,
    
}


##41
PACKET_INFO[ TAG_CHAT_PACKET_TYPE.TAG_CHAT_TAG_REGISTER ] = \
{

	"FORMAT":[
		PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.USER_ID,
		PACKET_ATTRIBUTE.TAG_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
		PACKET_ATTRIBUTE.PACKET_ID,
        PACKET_ATTRIBUTE.PLATFORM
	],
    "CONFIRMATION" : True,
    "BROKEN" : False,
}

##42
PACKET_INFO[ TAG_CHAT_PACKET_TYPE.TAG_CHAT_TAG_UNREGISTER] = \
{

    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.USER_ID,
        PACKET_ATTRIBUTE.TAG_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID,
        PACKET_ATTRIBUTE.ONLINE_STATUS,
        PACKET_ATTRIBUTE.USER_MOOD

    ],
    "CONFIRMATION" : False,
    "BROKEN" : False,
}


##43
PACKET_INFO[ TAG_CHAT_PACKET_TYPE.TAG_CHAT_TAG_REGISTER_CONFIRMATION ] = \
{

    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.TAG_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID,
        PACKET_ATTRIBUTE.CHAT_BINDING_PORT,
        PACKET_ATTRIBUTE.SERVER_DATE
    ],
    "CONFIRMATION" : False,
    "BROKEN" : False,
}

##46
PACKET_INFO[ TAG_CHAT_PACKET_TYPE.TAG_CHAT_TAG_INFORMATION ] = \
{

    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.USER_ID,
        PACKET_ATTRIBUTE.TAG_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID,
        PACKET_ATTRIBUTE.ACTIVITY_TYPE,
        PACKET_ATTRIBUTE.TAG_NAME_LENGTH,
        PACKET_ATTRIBUTE.TAG_NAME,
        PACKET_ATTRIBUTE.TAG_PICTURE_URL_LENGTH,
        PACKET_ATTRIBUTE.TAG_PICTURE_URL

    ],
    "CONFIRMATION" : False,
    "BROKEN" : False,
    
}

##47
PACKET_INFO[ TAG_CHAT_PACKET_TYPE.TAG_CHAT_TAG_INFORMATION_CONFIRMATION ] = \
{

    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.USER_ID,
        PACKET_ATTRIBUTE.TAG_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID

    ],
    "CONFIRMATION" : False,
    "BROKEN" : False,
}

##51
PACKET_INFO[ TAG_CHAT_PACKET_TYPE.TAG_CHAT_TAG_MEMBER_ADD ] = \
{

    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.USER_ID,
        PACKET_ATTRIBUTE.TAG_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID,
        PACKET_ATTRIBUTE.TAG_NO_OF_MEMBERS,
        [
            PACKET_ATTRIBUTE.USER_ID,
            PACKET_ATTRIBUTE.FULL_NAME_LENGTH,
            PACKET_ATTRIBUTE.FULL_NAME,
            PACKET_ATTRIBUTE.TAG_MEMBER_TYPE
        ]

    ],
    "CONFIRMATION" : True,
    "BROKEN" : True,
}

##52
PACKET_INFO[ TAG_CHAT_PACKET_TYPE.TAG_CHAT_TAG_MEMBER_ADD_CONFIRMATION ] = \
{

    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.USER_ID,
        PACKET_ATTRIBUTE.TAG_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID

    ],
    "CONFIRMATION" : True,
    "BROKEN" : False,
}

##53
PACKET_INFO[ TAG_CHAT_PACKET_TYPE.TAG_CHAT_MEMBER_REMOVE_LEAVE ] = \
{

    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.USER_ID,
        PACKET_ATTRIBUTE.TAG_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID,
        PACKET_ATTRIBUTE.TAG_NO_OF_MEMBERS,
        [
            PACKET_ATTRIBUTE.USER_ID
        ]
    ],
    "CONFIRMATION" : True,
    "BROKEN" : True,
}

##54
PACKET_INFO[ TAG_CHAT_PACKET_TYPE.TAG_CHAT_MEMBER_REMOVE_LEAVE_CONFIRMATION ] = \
{

    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.USER_ID,
        PACKET_ATTRIBUTE.TAG_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID
    ],
    "CONFIRMATION" : True,
    "BROKEN" : False,
}

##55
PACKET_INFO[ TAG_CHAT_PACKET_TYPE.TAG_CHAT_TAG_MEMBER_TYPE_CHANGE ] = \
{

    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.USER_ID,
        PACKET_ATTRIBUTE.TAG_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID,
        PACKET_ATTRIBUTE.TAG_NO_OF_MEMBERS,
        [
            PACKET_ATTRIBUTE.USER_ID,
            PACKET_ATTRIBUTE.TAG_MEMBER_TYPE
        ]

    ],
    "CONFIRMATION" : True,
    "BROKEN" : True,
}

##56
PACKET_INFO[ TAG_CHAT_PACKET_TYPE.TAG_CHAT_TAG_MEMBER_TYPE_CHANGE_CONFIRMATION] = \
{

    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.USER_ID,
        PACKET_ATTRIBUTE.TAG_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID

    ],
    "CONFIRMATION" : False,
    "BROKEN" : False,
}



##61
PACKET_INFO[ TAG_CHAT_PACKET_TYPE.TAG_CHAT_IDLE ] = \
{

    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.USER_ID,
        PACKET_ATTRIBUTE.TAG_ID,
        PACKET_ATTRIBUTE.PLATFORM
    ],
    "CONFIRMATION" : False,
    "BROKEN" : False,
}

##62
PACKET_INFO[ TAG_CHAT_PACKET_TYPE.TAG_CHAT_TYPING ] = \
{

    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.USER_ID,
        PACKET_ATTRIBUTE.TAG_ID,
        PACKET_ATTRIBUTE.PLATFORM

    ],
    "CONFIRMATION" : False,
    "BROKEN" : False,

}

##63
PACKET_INFO[ TAG_CHAT_PACKET_TYPE.TAG_CHAT_MSG ] = \
{
    "BROKEN_CONTAINER" : 'message',
    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.USER_ID,
        PACKET_ATTRIBUTE.TAG_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID,
        PACKET_ATTRIBUTE.MESSAGE_TYPE,
        PACKET_ATTRIBUTE.MESSAGE_LENGTH,
        PACKET_ATTRIBUTE.MESSAGE,
        PACKET_ATTRIBUTE.MESSAGE_DATE

    ],
    "CONFIRMATION" : True,
    "BROKEN" : True,
}

##64
PACKET_INFO[ TAG_CHAT_PACKET_TYPE.TAG_CHAT_MSG_EDIT ] = \
{

    "BROKEN_CONTAINER" : 'message',
    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.USER_ID,
        PACKET_ATTRIBUTE.TAG_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID,
        PACKET_ATTRIBUTE.MESSAGE_TYPE,
        PACKET_ATTRIBUTE.MESSAGE_LENGTH,
        PACKET_ATTRIBUTE.MESSAGE,
        PACKET_ATTRIBUTE.MESSAGE_DATE

    ],
    "CONFIRMATION" : True,
    "BROKEN" : True,
}


##65
PACKET_INFO[ TAG_CHAT_PACKET_TYPE.TAG_CHAT_BROKEN_MSG ] = \
{

    "BROKEN_CONTAINER" : 'message',
    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.USER_ID,
        PACKET_ATTRIBUTE.TAG_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID,
        PACKET_ATTRIBUTE.NO_OF_PACKET,
        PACKET_ATTRIBUTE.SEQUENCE_NO,
        PACKET_ATTRIBUTE.MESSAGE_TYPE,
        PACKET_ATTRIBUTE.MESSAGE_LENGTH,
        PACKET_ATTRIBUTE.MESSAGE,
        PACKET_ATTRIBUTE.MESSAGE_DATE

    ],
    "CONFIRMATION" : True,
    "BROKEN" : False,
}

##66
PACKET_INFO[ TAG_CHAT_PACKET_TYPE.TAG_CHAT_BROKEN_MSG_EDIT ] = \
{

    "BROKEN_CONTAINER" : 'message',
    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.USER_ID,
        PACKET_ATTRIBUTE.TAG_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID,
        PACKET_ATTRIBUTE.NO_OF_PACKET,
        PACKET_ATTRIBUTE.SEQUENCE_NO,
        PACKET_ATTRIBUTE.MESSAGE_TYPE,
        PACKET_ATTRIBUTE.MESSAGE_LENGTH,
        PACKET_ATTRIBUTE.MESSAGE,
        PACKET_ATTRIBUTE.MESSAGE_DATE

    ],
    "CONFIRMATION" : True,
    "BROKEN" : False,
}

##67
PACKET_INFO[ TAG_CHAT_PACKET_TYPE.TAG_CHAT_MULTIPLE_MSG ] = \
{

    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.USER_ID,
        PACKET_ATTRIBUTE.TAG_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID,
        PACKET_ATTRIBUTE.NO_OF_MESSAGE,
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID,
        PACKET_ATTRIBUTE.MESSAGE_TYPE,
        PACKET_ATTRIBUTE.MESSAGE_LENGTH,
        PACKET_ATTRIBUTE.MESSAGE,
        PACKET_ATTRIBUTE.MESSAGE_DATE

    ],
    "CONFIRMATION" : True,
    "BROKEN" : True,
}



 ##68
PACKET_INFO[ TAG_CHAT_PACKET_TYPE.TAG_CHAT_DELIVERED ] = \
{

	"FORMAT":[
		PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.USER_ID,
		PACKET_ATTRIBUTE.FRIEND_ID,
        PACKET_ATTRIBUTE.TAG_ID,
		PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID
	],
    "CONFIRMATION" : False,
    "BROKEN" : False,
}

##69
PACKET_INFO[ TAG_CHAT_PACKET_TYPE.TAG_CHAT_SENT ] = \
{

    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.TAG_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID
    ],
    "CONFIRMATION" : False,
    "BROKEN" : False,
}

##70
PACKET_INFO[ TAG_CHAT_PACKET_TYPE.TAG_CHAT_SEEN ] = \
{

	"FORMAT":[
		PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.USER_ID,
		PACKET_ATTRIBUTE.FRIEND_ID,
        PACKET_ATTRIBUTE.TAG_ID,
		PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID
	],
    "CONFIRMATION" : False,
    "BROKEN" : False,
}

##71
PACKET_INFO[ TAG_CHAT_PACKET_TYPE.TAG_CHAT_SEEN_CONFIRMATION ] = \
{

    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.TAG_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID
    ],
    "CONFIRMATION" : False,
    "BROKEN" : False,
}


##72
PACKET_INFO[ TAG_CHAT_PACKET_TYPE.TAG_CHAT_MULTIPLE_MSG_DELETE ] = \
{

    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.USER_ID,
        PACKET_ATTRIBUTE.TAG_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID,
        PACKET_ATTRIBUTE.NO_OF_PACKET,
        [
            PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            PACKET_ATTRIBUTE.PACKET_ID
        ]

    ],
    "CONFIRMATION" : True,
    "BROKEN" : True,
}



##73
PACKET_INFO[ TAG_CHAT_PACKET_TYPE.TAG_CHAT_MSG_DELETE_CONFIRMATION ] = \
{

	"FORMAT":[
		PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.USER_ID,
        PACKET_ATTRIBUTE.TAG_ID,
		PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID
	],
    "CONFIRMATION" : False,
    "BROKEN" : False,
}



##74
PACKET_INFO[ TAG_CHAT_PACKET_TYPE.TAG_CHAT_GENERAL_BROKEN_PACKET] = \
{
    "BROKEN_CONTAINER" : 'bytes',
    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.USER_ID,
        PACKET_ATTRIBUTE.TAG_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID,
        PACKET_ATTRIBUTE.NO_OF_PACKET,
        PACKET_ATTRIBUTE.SEQUENCE_NO,
        PACKET_ATTRIBUTE.RAW_DATA_BYTE


    ],
    "CONFIRMATION" : True,
    "BROKEN" : False,
}


##75
PACKET_INFO[ TAG_CHAT_PACKET_TYPE.TAG_CHAT_GENERAL_BROKEN_PACKET_CONFIRMATION] = \
{

    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.USER_ID,
        PACKET_ATTRIBUTE.TAG_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID,
        PACKET_ATTRIBUTE.SEQUENCE_NO
    ],
    "CONFIRMATION" : False,
    "BROKEN" : False,
}


##91
PACKET_INFO[ OFFLINE_PACKET_TYPE.OFFLINE_FRIEND_INFORMATION] = \
{

    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.USER_ID,
        PACKET_ATTRIBUTE.FRIEND_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID,
        PACKET_ATTRIBUTE.FULL_NAME_LENGTH,
        PACKET_ATTRIBUTE.FULL_NAME,
        PACKET_ATTRIBUTE.PLATFORM,
        PACKET_ATTRIBUTE.ONLINE_STATUS,
        PACKET_ATTRIBUTE.FRIEND_APP_TYPE,
        PACKET_ATTRIBUTE.FRIEND_DEVICE_TOKEN_LENGTH,
        PACKET_ATTRIBUTE.FRIEND_DEVICE_TOKEN,
        PACKET_ATTRIBUTE.USER_MOOD
    ],
    "CONFIRMATION" : True,
    "BROKEN" : False,
}

##92
PACKET_INFO[ OFFLINE_PACKET_TYPE.OFFLINE_FRIEND_INFORMATION_CONFIRMATION] = \
{

    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.FRIEND_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID,
        PACKET_ATTRIBUTE.PLATFORM
    ],
    "CONFIRMATION" : False,
    "BROKEN" : False,
}


##93
PACKET_INFO[ OFFLINE_PACKET_TYPE.OFFLINE_GET_REQUEST] = \
{

    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.USER_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID,
        PACKET_ATTRIBUTE.UPDATE_TIME,
        PACKET_ATTRIBUTE.BLOCK_UNBLOCK_DATE,
        PACKET_ATTRIBUTE.APP_VERSION,
        PACKET_ATTRIBUTE.PLATFORM
    ],
    "CONFIRMATION" : True,
    "BROKEN" : False,
}


##94
PACKET_INFO[ OFFLINE_PACKET_TYPE.OFFLINE_GET_REQUEST_CONFIRMATION] = \
{

    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID,
        PACKET_ATTRIBUTE.SERVER_DATE
    ],
    "CONFIRMATION" : False,
    "BROKEN" : False,
}


##95
PACKET_INFO[ OFFLINE_PACKET_TYPE.OFFLINE_FRIEND_UNREAD_MESSAGE] = \
{

    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID,
        PACKET_ATTRIBUTE.NO_OF_MESSAGE,
        [
            PACKET_ATTRIBUTE.PACKET_TYPE,
            PACKET_ATTRIBUTE.USER_ID,
            PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            PACKET_ATTRIBUTE.PACKET_ID,
            PACKET_ATTRIBUTE.MESSAGE_TYPE,
            PACKET_ATTRIBUTE.TIMEOUT,
            PACKET_ATTRIBUTE.MESSAGE_LENGTH,
            PACKET_ATTRIBUTE.MESSAGE,
            PACKET_ATTRIBUTE.MESSAGE_DATE,
            PACKET_ATTRIBUTE.IS_SECRET_VISIBLE
        ]

    ],
    "CONFIRMATION" : True,
    "BROKEN" : False,
}



##96
PACKET_INFO[ OFFLINE_PACKET_TYPE.OFFLINE_FRIEND_UNREAD_MESSAGE_CONFIRMATION] = \
{
    "BROKEN_CONTAINER" : 'packets',
    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.USER_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID,
        PACKET_ATTRIBUTE.NO_OF_PACKET,
        [
            PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            PACKET_ATTRIBUTE.PACKET_ID
        ]


    ],
    "CONFIRMATION" : False,
    "BROKEN" : False,
}

##97
PACKET_INFO[ OFFLINE_PACKET_TYPE.OFFLINE_FRIEND_HISTORY_MESSAGE_REQUEST] = \
{

    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.USER_ID,
        PACKET_ATTRIBUTE.FRIEND_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID,
        PACKET_ATTRIBUTE.PAGE_DIRECTION,
        PACKET_ATTRIBUTE.PAGE_LIMIT,
        #PACKET_ATTRIBUTE.APP_VERSION,
        PACKET_ATTRIBUTE.PLATFORM
    ],
    "CONFIRMATION" : True,
    "BROKEN" : False,
}

##98
PACKET_INFO[ OFFLINE_PACKET_TYPE.OFFLINE_FRIEND_HISTORY_MESSAGE] = \
{

    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.FRIEND_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID,
        PACKET_ATTRIBUTE.NO_OF_MESSAGE,
        [
            PACKET_ATTRIBUTE.PACKET_TYPE,
            PACKET_ATTRIBUTE.USER_ID,
            PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            PACKET_ATTRIBUTE.PACKET_ID,
            PACKET_ATTRIBUTE.MESSAGE_TYPE,
            PACKET_ATTRIBUTE.TIMEOUT,
            PACKET_ATTRIBUTE.MESSAGE_LENGTH,
            PACKET_ATTRIBUTE.MESSAGE,
            PACKET_ATTRIBUTE.MESSAGE_DATE,
            PACKET_ATTRIBUTE.IS_SECRET_VISIBLE,
            PACKET_ATTRIBUTE.MESSAGE_STATUS
        ],
        PACKET_ATTRIBUTE.PAGE_DIRECTION
    ],
    "CONFIRMATION" : False,
    "BROKEN" : False,
}

##99
PACKET_INFO[ OFFLINE_PACKET_TYPE.OFFLINE_FRIEND_HISTORY_MESSAGE_CONFIRMATION] = \
{

    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.FRIEND_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID

    ],
    "CONFIRMATION" : False,
    "BROKEN" : False,
}


##100
PACKET_INFO[ OFFLINE_PACKET_TYPE.OFFLINE_GET_FRIEND_MESSAGE_STATUS] = \
{

    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.USER_ID,
        PACKET_ATTRIBUTE.FRIEND_ID,
        PACKET_ATTRIBUTE.PACKET_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.NO_OF_PACKET,
        [
            PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            PACKET_ATTRIBUTE.PACKET_ID
        ],
        PACKET_ATTRIBUTE.PLATFORM


    ],
    "CONFIRMATION" : True,
    "BROKEN" : True,
}

##101
PACKET_INFO[ OFFLINE_PACKET_TYPE.OFFLINE_GET_FRIEND_MESSAGE_STATUS_CONFIRMATION] = \
{

    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.FRIEND_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID,
        PACKET_ATTRIBUTE.NO_OF_PACKET,
        [
            PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            PACKET_ATTRIBUTE.PACKET_ID
        ]

    ],
    "CONFIRMATION" : True,
    "BROKEN" : False,
}



# #104
PACKET_INFO[ OFFLINE_PACKET_TYPE.OFFLINE_TAG_INFORMATION_ACTIVITY ] = \
{

    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.TAG_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID,
        PACKET_ATTRIBUTE.NO_OF_ITEMS,
        [
            PACKET_ATTRIBUTE.ACTIVITY_TYPE,
            PACKET_ATTRIBUTE.USER_ID,
            PACKET_ATTRIBUTE.ACTIVITY_VALUE_LENGTH,
            PACKET_ATTRIBUTE.ACTIVITY_VALUE,
            PACKET_ATTRIBUTE.TAG_MEMBER_TYPE,
            PACKET_ATTRIBUTE.CHANGED_BY_USER_ID,
            PACKET_ATTRIBUTE.UPDATE_TIME
        ]

    ],
    "CONFIRMATION" : False,
    "BROKEN" : False,
}

##105
PACKET_INFO[ OFFLINE_PACKET_TYPE.OFFLINE_MY_TAG_LIST ] = \
{
    "BROKEN_CONTAINER" : "items",
    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID,
        PACKET_ATTRIBUTE.NO_OF_ITEMS,
        [
            PACKET_ATTRIBUTE.TAG_ID,
            PACKET_ATTRIBUTE.TAG_NAME_LENGTH,
            PACKET_ATTRIBUTE.TAG_NAME,
            PACKET_ATTRIBUTE.TAG_PICTURE_URL_LENGTH,
            PACKET_ATTRIBUTE.TAG_PICTURE_URL,
            PACKET_ATTRIBUTE.TAG_MEMBER_ADDED_BY,
            PACKET_ATTRIBUTE.TAG_INFORMATION_TAG_NO_OF_MEMBERS
        ]

    ],
    "CONFIRMATION" : False,
    "BROKEN" : False,
}



##106
PACKET_INFO[ OFFLINE_PACKET_TYPE.OFFLINE_TAG_UNREAD_MESSAGE] = \
{

    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID,
        PACKET_ATTRIBUTE.NO_OF_MESSAGE,
        [
            PACKET_ATTRIBUTE.PACKET_TYPE,
            PACKET_ATTRIBUTE.USER_ID,
            PACKET_ATTRIBUTE.TAG_ID,
            PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            PACKET_ATTRIBUTE.PACKET_ID,
            PACKET_ATTRIBUTE.MESSAGE_TYPE,
            PACKET_ATTRIBUTE.MESSAGE_LENGTH,
            PACKET_ATTRIBUTE.MESSAGE,
            PACKET_ATTRIBUTE.MESSAGE_DATE

        ]

    ],
    "CONFIRMATION" : False,
    "BROKEN" : False,
}


##107
PACKET_INFO[ OFFLINE_PACKET_TYPE.OFFLINE_TAG_UNREAD_MESSAGE_CONFIRMATION] = \
{

    "BROKEN_CONTAINER" : 'packets',
    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.USER_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID,
        PACKET_ATTRIBUTE.NO_OF_PACKET,
        [
            PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            PACKET_ATTRIBUTE.PACKET_ID
        ]


    ],
    "CONFIRMATION" : False,
    "BROKEN" : True,
}

##108
PACKET_INFO[ OFFLINE_PACKET_TYPE.OFFLINE_TAG_CREATE_TAG ] = \
{

    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.USER_ID,
        PACKET_ATTRIBUTE.TAG_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID,
        PACKET_ATTRIBUTE.TAG_NAME_LENGTH,
        PACKET_ATTRIBUTE.TAG_NAME,
        PACKET_ATTRIBUTE.TAG_PICTURE_URL_LENGTH,
        PACKET_ATTRIBUTE.TAG_PICTURE_URL,
        PACKET_ATTRIBUTE.TAG_NO_OF_MEMBERS,
        [
            PACKET_ATTRIBUTE.USER_ID,
            PACKET_ATTRIBUTE.FULL_NAME_LENGTH,
            PACKET_ATTRIBUTE.FULL_NAME,
            PACKET_ATTRIBUTE.TAG_MEMBER_TYPE
        ],
        PACKET_ATTRIBUTE.PLATFORM
    ],
    "CONFIRMATION" : True,
    "BROKEN" : True,
}

##109
PACKET_INFO[ OFFLINE_PACKET_TYPE.OFFLINE_TAG_CREATE_TAG_CONFIRMATION ] = \
{

    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.TAG_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID
    ],
    "CONFIRMATION" : False,
    "BROKEN" : False,

}


##110
PACKET_INFO[ OFFLINE_PACKET_TYPE.OFFLINE_TAG_HISTORY_MESSAGE_REQUEST] = \
{

    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.USER_ID,
        PACKET_ATTRIBUTE.TAG_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID,
        PACKET_ATTRIBUTE.PAGE_DIRECTION,
        PACKET_ATTRIBUTE.PAGE_LIMIT,
        PACKET_ATTRIBUTE.APP_VERSION,
        PACKET_ATTRIBUTE.PLATFORM

    ],
    "CONFIRMATION" : True,
    "BROKEN" : False,
}


##111
PACKET_INFO[ OFFLINE_PACKET_TYPE.OFFLINE_TAG_HISTORY_MESSAGE] = \
{

    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.TAG_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID,
        PACKET_ATTRIBUTE.NO_OF_MESSAGE,
        [
            PACKET_ATTRIBUTE.PACKET_TYPE,
            PACKET_ATTRIBUTE.USER_ID,
            PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            PACKET_ATTRIBUTE.PACKET_ID,
            PACKET_ATTRIBUTE.MESSAGE_TYPE,
            PACKET_ATTRIBUTE.MESSAGE_LENGTH,
            PACKET_ATTRIBUTE.MESSAGE,
            PACKET_ATTRIBUTE.MESSAGE_DATE
        ],
        PACKET_ATTRIBUTE.PAGE_DIRECTION
    ],
    "CONFIRMATION" : False,
    "BROKEN" : False,
}

##112
PACKET_INFO[ OFFLINE_PACKET_TYPE.OFFLINE_GET_TAG_INFORMATION_WITH_MEMBERS ] = \
{

    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.USER_ID,
        PACKET_ATTRIBUTE.TAG_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID,
        PACKET_ATTRIBUTE.PLATFORM
    ],
    "CONFIRMATION" : True,
    "BROKEN" : False,
}

##113
PACKET_INFO[ OFFLINE_PACKET_TYPE.OFFLINE_TAG_INFORMATION_WITH_MEMBERS ] = \
{

    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.TAG_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID,
        PACKET_ATTRIBUTE.TAG_NAME_LENGTH,
        PACKET_ATTRIBUTE.TAG_NAME,
        PACKET_ATTRIBUTE.TAG_PICTURE_URL_LENGTH,
        PACKET_ATTRIBUTE.TAG_PICTURE_URL,
        PACKET_ATTRIBUTE.TAG_NO_OF_MEMBERS,
        [
            PACKET_ATTRIBUTE.USER_ID,
            PACKET_ATTRIBUTE.FULL_NAME_LENGTH,
            PACKET_ATTRIBUTE.FULL_NAME,
            PACKET_ATTRIBUTE.TAG_MEMBER_TYPE,
            PACKET_ATTRIBUTE.TAG_MEMBER_ADDED_BY
        ]
    ],
    "CONFIRMATION" : True,
    "BROKEN" : False,
}


##117
PACKET_INFO[ OFFLINE_PACKET_TYPE.OFFLINE_TAG_CONFIRMATION] = \
{

    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.TAG_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID

    ],
    "CONFIRMATION" : False,
    "BROKEN" : False,
}



##118
PACKET_INFO[ OFFLINE_PACKET_TYPE.OFFLINE_BROKEN_HISTORY_PACKET] = \
{

    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID,
        PACKET_ATTRIBUTE.NO_OF_PACKET,
        PACKET_ATTRIBUTE.SEQUENCE_NO,
        PACKET_ATTRIBUTE.RAW_DATA_BYTE


    ],
    "CONFIRMATION" : True,
    "BROKEN" : False,
}

##119
PACKET_INFO[ OFFLINE_PACKET_TYPE.OFFLINE_BROKEN_PACKET] = \
{

    "BROKEN_CONTAINER" : 'bytes',
    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID,
        PACKET_ATTRIBUTE.NO_OF_PACKET,
        PACKET_ATTRIBUTE.SEQUENCE_NO,
        PACKET_ATTRIBUTE.RAW_DATA_BYTE,
        PACKET_ATTRIBUTE.USER_ID,
        PACKET_ATTRIBUTE.PLATFORM

    ],
    "CONFIRMATION" : True,
    "BROKEN" : False,
}


##120
PACKET_INFO[ OFFLINE_PACKET_TYPE.OFFLINE_BROKEN_PACKET_CONFIRMATION] = \
{

    "FORMAT":[
        PACKET_ATTRIBUTE.PACKET_TYPE,
        PACKET_ATTRIBUTE.USER_ID,
        PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
        PACKET_ATTRIBUTE.PACKET_ID,
        PACKET_ATTRIBUTE.SEQUENCE_NO

    ],
    "CONFIRMATION" : False,
    "BROKEN" : False,
}

# for i in PACKET_INFO:
# 	PACKET_INFO[i]["FORMAT"]= obj(PACKET_INFO[i])


METHOD_IGNORE_ATTRIBUTE = [
	PACKET_ATTRIBUTE.PACKET_TYPE,
	PACKET_ATTRIBUTE.APP_VERSION,
	PACKET_ATTRIBUTE.USER_ID,
	PACKET_ATTRIBUTE.PLATFORM,
]

REQUEST_IGNORE_ATTRIBUTE = [
	PACKET_ATTRIBUTE.PACKET_TYPE,	
]


MAX_ATTR_SIZE = 0
for attr_no, value in PACKET_ATTRIBUTE_INFO.iteritems():
    if "VAR_NAME" not in value:
        value["VAR_NAME"] = getCamleCase(PACKET_ATTRIBUTE_NAME_MAP[attr_no])

	MAX_ATTR_SIZE = max(MAX_ATTR_SIZE, len(value["VAR_NAME"]))
	if( "VAR_CONTAINER_NAME" in value ):
		MAX_ATTR_SIZE = max(MAX_ATTR_SIZE, len(value["VAR_CONTAINER_NAME"]))


AUTH_SERVER_ACTIONS_OBJECT = {
    "START_F2F_CHAT"          : 175,
    "RECEIVED_F2F_CHAT"       : 375,
    "START_TAG_CHAT"          : 134,
    "RECEIVED_TAG_CHAT"       : 334,
    "ADD_TAG_CHAT_MEMBERS"    : 135,
    "GET_OFFLINE_IP_PORT"     : 83
}

AUTH_SERVER_ACTIONS = obj(AUTH_SERVER_ACTIONS_OBJECT);




