(function PublicChatPacketFormatIIFE(global) {
    /** ***********************************************  PACKET FORMAT DEFINITION ***********************************/

    var ChatConstants = global.CHAT_APP.Constants,
        PUBLIC_CHAT_ONLINE_PACKET_TYPE = ChatConstants.PUBLIC_CHAT_ONLINE_PACKET_TYPE,
        PUBLIC_CHAT_OFFLINE_PACKET_TYPE = ChatConstants.PUBLIC_CHAT_OFFLINE_PACKET_TYPE,
        PUBLIC_CHAT_PACKET_INFO = {},
        CHAT_PACKET_ATTRIBUTE = global.CHAT_APP.PacketFormats.CHAT_PACKET_ATTRIBUTE;


    // PACKET TYPE(1001) : PUBLIC_CHAT_REGISTER
    PUBLIC_CHAT_PACKET_INFO[PUBLIC_CHAT_ONLINE_PACKET_TYPE.PUBLIC_CHAT_REGISTER] = {
        PACKET_NAME: 'PUBLIC_CHAT_REGISTER',
        CONFIRMATION: true,
        BROKEN: false,
        FORMAT: [
            CHAT_PACKET_ATTRIBUTE.PACKET_TYPE,
            CHAT_PACKET_ATTRIBUTE.USER_ID,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID,
            CHAT_PACKET_ATTRIBUTE.FULL_NAME_LENGTH,
            CHAT_PACKET_ATTRIBUTE.FULL_NAME,
            CHAT_PACKET_ATTRIBUTE.MEMBER_URL_LENGTH,
            CHAT_PACKET_ATTRIBUTE.MEMBER_URL,
            CHAT_PACKET_ATTRIBUTE.PLATFORM,

        ],
    };

    // PACKET TYPE(1002) : PUBLIC_CHAT_UNREGISTER
    PUBLIC_CHAT_PACKET_INFO[PUBLIC_CHAT_ONLINE_PACKET_TYPE.PUBLIC_CHAT_UNREGISTER] = {
        PACKET_NAME: 'PUBLIC_CHAT_UNREGISTER',
        CONFIRMATION: false,
        BROKEN: false,
        FORMAT: [
            CHAT_PACKET_ATTRIBUTE.PACKET_TYPE,
            CHAT_PACKET_ATTRIBUTE.USER_ID,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID,

        ],
    };

    // PACKET TYPE(1003) : PUBLIC_CHAT_REGISTER_CONFIRMATION
    PUBLIC_CHAT_PACKET_INFO[PUBLIC_CHAT_ONLINE_PACKET_TYPE.PUBLIC_CHAT_REGISTER_CONFIRMATION] = {
        PACKET_NAME: 'PUBLIC_CHAT_REGISTER_CONFIRMATION',
        CONFIRMATION: false,
        BROKEN: false,
        FORMAT: [
            CHAT_PACKET_ATTRIBUTE.PACKET_TYPE,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID,
            CHAT_PACKET_ATTRIBUTE.CHAT_BINDING_PORT,
            CHAT_PACKET_ATTRIBUTE.SHADOW_ID,

        ],
    };

    // PACKET TYPE(1004) : PUBLIC_CHAT_CHAT_IDEL
    PUBLIC_CHAT_PACKET_INFO[PUBLIC_CHAT_ONLINE_PACKET_TYPE.PUBLIC_CHAT_CHAT_IDEL] = {
        PACKET_NAME: 'PUBLIC_CHAT_CHAT_IDEL',
        CONFIRMATION: false,
        BROKEN: false,
        FORMAT: [
            CHAT_PACKET_ATTRIBUTE.PACKET_TYPE,
            CHAT_PACKET_ATTRIBUTE.USER_ID,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID,
            CHAT_PACKET_ATTRIBUTE.PLATFORM,

        ],
    };

    // PACKET TYPE(1005) : PUBLIC_CHAT_CHAT_MESSAGE_TYPING
    PUBLIC_CHAT_PACKET_INFO[PUBLIC_CHAT_ONLINE_PACKET_TYPE.PUBLIC_CHAT_CHAT_MESSAGE_TYPING] = {
        PACKET_NAME: 'PUBLIC_CHAT_CHAT_MESSAGE_TYPING',
        CONFIRMATION: false,
        BROKEN: false,
        FORMAT: [
            CHAT_PACKET_ATTRIBUTE.PACKET_TYPE,
            CHAT_PACKET_ATTRIBUTE.USER_ID,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID,
            CHAT_PACKET_ATTRIBUTE.PLATFORM,
            CHAT_PACKET_ATTRIBUTE.FULL_NAME_LENGTH,
            CHAT_PACKET_ATTRIBUTE.FULL_NAME,

        ],
    };

    // PACKET TYPE(1006) : PUBLIC_CHAT_CHAT_MESSAGE
    PUBLIC_CHAT_PACKET_INFO[PUBLIC_CHAT_ONLINE_PACKET_TYPE.PUBLIC_CHAT_CHAT_MESSAGE] = {
        PACKET_NAME: 'PUBLIC_CHAT_CHAT_MESSAGE',
        BROKEN_CONTAINER: 'message',
        CONFIRMATION: true,
        BROKEN: true,
        FORMAT: [
            CHAT_PACKET_ATTRIBUTE.PACKET_TYPE,
            CHAT_PACKET_ATTRIBUTE.USER_ID,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID,
            CHAT_PACKET_ATTRIBUTE.MESSAGE_TYPE,
            CHAT_PACKET_ATTRIBUTE.MESSAGE_LENGTH,
            CHAT_PACKET_ATTRIBUTE.MESSAGE,
            CHAT_PACKET_ATTRIBUTE.MESSAGE_DATE,
            CHAT_PACKET_ATTRIBUTE.FULL_NAME_LENGTH,
            CHAT_PACKET_ATTRIBUTE.FULL_NAME,
            CHAT_PACKET_ATTRIBUTE.MEMBER_URL_LENGTH,
            CHAT_PACKET_ATTRIBUTE.MEMBER_URL,

        ],
    };

    // PACKET TYPE(1007) : PUBLIC_CHAT_CHAT_MESSAGE_EDIT
    PUBLIC_CHAT_PACKET_INFO[PUBLIC_CHAT_ONLINE_PACKET_TYPE.PUBLIC_CHAT_CHAT_MESSAGE_EDIT] = {
        PACKET_NAME: 'PUBLIC_CHAT_CHAT_MESSAGE_EDIT',
        BROKEN_CONTAINER: 'message',
        CONFIRMATION: true,
        BROKEN: true,
        FORMAT: [
            CHAT_PACKET_ATTRIBUTE.PACKET_TYPE,
            CHAT_PACKET_ATTRIBUTE.USER_ID,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID,
            CHAT_PACKET_ATTRIBUTE.MESSAGE_TYPE,
            CHAT_PACKET_ATTRIBUTE.MESSAGE_LENGTH,
            CHAT_PACKET_ATTRIBUTE.MESSAGE,
            CHAT_PACKET_ATTRIBUTE.MESSAGE_DATE,
            CHAT_PACKET_ATTRIBUTE.FULL_NAME_LENGTH,
            CHAT_PACKET_ATTRIBUTE.FULL_NAME,
            CHAT_PACKET_ATTRIBUTE.MEMBER_URL_LENGTH,
            CHAT_PACKET_ATTRIBUTE.MEMBER_URL,

        ],
    };

    // PACKET TYPE(1008) : PUBLIC_CHAT_CHAT_MESSAGE_BROKEN
    PUBLIC_CHAT_PACKET_INFO[PUBLIC_CHAT_ONLINE_PACKET_TYPE.PUBLIC_CHAT_CHAT_MESSAGE_BROKEN] = {
        PACKET_NAME: 'PUBLIC_CHAT_CHAT_MESSAGE_BROKEN',
        BROKEN_CONTAINER: 'message',
        CONFIRMATION: true,
        BROKEN: false,
        FORMAT: [
            CHAT_PACKET_ATTRIBUTE.PACKET_TYPE,
            CHAT_PACKET_ATTRIBUTE.USER_ID,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID,
            CHAT_PACKET_ATTRIBUTE.NO_OF_PACKET,
            CHAT_PACKET_ATTRIBUTE.SEQUENCE_NO,
            CHAT_PACKET_ATTRIBUTE.MESSAGE_TYPE,
            CHAT_PACKET_ATTRIBUTE.MESSAGE_LENGTH,
            CHAT_PACKET_ATTRIBUTE.MESSAGE,
            CHAT_PACKET_ATTRIBUTE.MESSAGE_DATE,
            CHAT_PACKET_ATTRIBUTE.FULL_NAME_LENGTH,
            CHAT_PACKET_ATTRIBUTE.FULL_NAME,
            CHAT_PACKET_ATTRIBUTE.MEMBER_URL_LENGTH,
            CHAT_PACKET_ATTRIBUTE.MEMBER_URL,

        ],
    };

    // PACKET TYPE(1009) : PUBLIC_CHAT_CHAT_MESSAGE_BROKEN_EDIT
    PUBLIC_CHAT_PACKET_INFO[PUBLIC_CHAT_ONLINE_PACKET_TYPE.PUBLIC_CHAT_CHAT_MESSAGE_BROKEN_EDIT] = {
        PACKET_NAME: 'PUBLIC_CHAT_CHAT_MESSAGE_BROKEN_EDIT',
        BROKEN_CONTAINER: 'message',
        CONFIRMATION: true,
        BROKEN: false,
        FORMAT: [
            CHAT_PACKET_ATTRIBUTE.PACKET_TYPE,
            CHAT_PACKET_ATTRIBUTE.USER_ID,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID,
            CHAT_PACKET_ATTRIBUTE.NO_OF_PACKET,
            CHAT_PACKET_ATTRIBUTE.SEQUENCE_NO,
            CHAT_PACKET_ATTRIBUTE.MESSAGE_TYPE,
            CHAT_PACKET_ATTRIBUTE.MESSAGE_LENGTH,
            CHAT_PACKET_ATTRIBUTE.MESSAGE,
            CHAT_PACKET_ATTRIBUTE.MESSAGE_DATE,
            CHAT_PACKET_ATTRIBUTE.FULL_NAME_LENGTH,
            CHAT_PACKET_ATTRIBUTE.FULL_NAME,
            CHAT_PACKET_ATTRIBUTE.MEMBER_URL_LENGTH,
            CHAT_PACKET_ATTRIBUTE.MEMBER_URL,

        ],
    };

    // PACKET TYPE(1010) : PUBLIC_CHAT_CHAT_MESSAGE_DELIVERED
    PUBLIC_CHAT_PACKET_INFO[PUBLIC_CHAT_ONLINE_PACKET_TYPE.PUBLIC_CHAT_CHAT_MESSAGE_DELIVERED] = {
        PACKET_NAME: 'PUBLIC_CHAT_CHAT_MESSAGE_DELIVERED',
        CONFIRMATION: false,
        BROKEN: false,
        FORMAT: [
            CHAT_PACKET_ATTRIBUTE.PACKET_TYPE,
            CHAT_PACKET_ATTRIBUTE.USER_ID,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID,

        ],
    };

    // PACKET TYPE(1011) : PUBLIC_CHAT_CHAT_MESSAGE_SENT
    PUBLIC_CHAT_PACKET_INFO[PUBLIC_CHAT_ONLINE_PACKET_TYPE.PUBLIC_CHAT_CHAT_MESSAGE_SENT] = {
        PACKET_NAME: 'PUBLIC_CHAT_CHAT_MESSAGE_SENT',
        CONFIRMATION: true,
        BROKEN: false,
        FORMAT: [
            CHAT_PACKET_ATTRIBUTE.PACKET_TYPE,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID,

        ],
    };

    // PACKET TYPE(1012) : PUBLIC_CHAT_GET_MEMBER_LIST
    PUBLIC_CHAT_PACKET_INFO[PUBLIC_CHAT_ONLINE_PACKET_TYPE.PUBLIC_CHAT_GET_MEMBER_LIST] = {
        PACKET_NAME: 'PUBLIC_CHAT_GET_MEMBER_LIST',
        CONFIRMATION: true,
        BROKEN: false,
        FORMAT: [
            CHAT_PACKET_ATTRIBUTE.PACKET_TYPE,
            CHAT_PACKET_ATTRIBUTE.USER_ID,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID,
            CHAT_PACKET_ATTRIBUTE.PAGING_STATE_LENGTH,
            CHAT_PACKET_ATTRIBUTE.PAGING_STATE,
            CHAT_PACKET_ATTRIBUTE.PAGE_LIMIT,

        ],
    };

    // PACKET TYPE(1013) : PUBLIC_CHAT_MEMBER_LIST_CONFIRMATION
    PUBLIC_CHAT_PACKET_INFO[PUBLIC_CHAT_ONLINE_PACKET_TYPE.PUBLIC_CHAT_MEMBER_LIST_CONFIRMATION] = {
        PACKET_NAME: 'PUBLIC_CHAT_MEMBER_LIST_CONFIRMATION',
        CONFIRMATION: false,
        BROKEN: false,
        FORMAT: [
            CHAT_PACKET_ATTRIBUTE.PACKET_TYPE,
            CHAT_PACKET_ATTRIBUTE.USER_ID,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID,

        ],
    };

    // PACKET TYPE(1014) : PUBLIC_CHAT_MEMBER_LIST
    PUBLIC_CHAT_PACKET_INFO[PUBLIC_CHAT_ONLINE_PACKET_TYPE.PUBLIC_CHAT_MEMBER_LIST] = {
        PACKET_NAME: 'PUBLIC_CHAT_MEMBER_LIST',
        CONFIRMATION: false,
        BROKEN: true,
        FORMAT: [
            CHAT_PACKET_ATTRIBUTE.PACKET_TYPE,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID,
            CHAT_PACKET_ATTRIBUTE.PAGING_STATE_LENGTH,
            CHAT_PACKET_ATTRIBUTE.PAGING_STATE,
            CHAT_PACKET_ATTRIBUTE.NO_OF_MEMBERS, [
                CHAT_PACKET_ATTRIBUTE.USER_ID,
                CHAT_PACKET_ATTRIBUTE.SHADOW_ID,
                CHAT_PACKET_ATTRIBUTE.FULL_NAME_LENGTH,
                CHAT_PACKET_ATTRIBUTE.FULL_NAME,
                CHAT_PACKET_ATTRIBUTE.MEMBER_URL_LENGTH,
                CHAT_PACKET_ATTRIBUTE.MEMBER_URL,
                CHAT_PACKET_ATTRIBUTE.ADDTIME,

            ],

        ],
    };

    // PACKET TYPE(1015) : PUBLIC_CHAT_MEMBER_COUNT_CHANGE
    PUBLIC_CHAT_PACKET_INFO[PUBLIC_CHAT_ONLINE_PACKET_TYPE.PUBLIC_CHAT_MEMBER_COUNT_CHANGE] = {
        PACKET_NAME: 'PUBLIC_CHAT_MEMBER_COUNT_CHANGE',
        CONFIRMATION: false,
        BROKEN: false,
        FORMAT: [
            CHAT_PACKET_ATTRIBUTE.PACKET_TYPE,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID,
            CHAT_PACKET_ATTRIBUTE.NO_OF_MEMBERS,

        ],
    };

    // PACKET TYPE(1016) : PUBLIC_CHAT_MEMBER_COUNT_CHANGE_CONFIRMATION
    PUBLIC_CHAT_PACKET_INFO[PUBLIC_CHAT_ONLINE_PACKET_TYPE.PUBLIC_CHAT_MEMBER_COUNT_CHANGE_CONFIRMATION] = {
        PACKET_NAME: 'PUBLIC_CHAT_MEMBER_COUNT_CHANGE_CONFIRMATION',
        CONFIRMATION: false,
        BROKEN: false,
        FORMAT: [
            CHAT_PACKET_ATTRIBUTE.PACKET_TYPE,
            CHAT_PACKET_ATTRIBUTE.USER_ID,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID,

        ],
    };

    // PACKET TYPE(1034) : PUBLIC_CHAT_DELETE_MESSAGE
    PUBLIC_CHAT_PACKET_INFO[PUBLIC_CHAT_ONLINE_PACKET_TYPE.PUBLIC_CHAT_DELETE_MESSAGE] = {
        PACKET_NAME: 'PUBLIC_CHAT_DELETE_MESSAGE',
        CONFIRMATION: false,
        BROKEN: true,
        FORMAT: [
            CHAT_PACKET_ATTRIBUTE.PACKET_TYPE,
            CHAT_PACKET_ATTRIBUTE.USER_ID,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID,
            CHAT_PACKET_ATTRIBUTE.NO_OF_PACKET, [
                CHAT_PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
                CHAT_PACKET_ATTRIBUTE.PACKET_ID,

            ],

        ],
    };

    // PACKET TYPE(1035) : PUBLIC_CHAT_DELETE_MESSAGE_CONFIRMATION
    PUBLIC_CHAT_PACKET_INFO[PUBLIC_CHAT_ONLINE_PACKET_TYPE.PUBLIC_CHAT_DELETE_MESSAGE_CONFIRMATION] = {
        PACKET_NAME: 'PUBLIC_CHAT_DELETE_MESSAGE_CONFIRMATION',
        CONFIRMATION: false,
        BROKEN: false,
        FORMAT: [
            CHAT_PACKET_ATTRIBUTE.PACKET_TYPE,
            CHAT_PACKET_ATTRIBUTE.USER_ID,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID,

        ],
    };


    // PACKET TYPE(1017) : PUBLIC_CHAT_ROOM_LIST_REQUEST
    PUBLIC_CHAT_PACKET_INFO[PUBLIC_CHAT_OFFLINE_PACKET_TYPE.PUBLIC_CHAT_ROOM_LIST_REQUEST] = {
        PACKET_NAME: 'PUBLIC_CHAT_ROOM_LIST_REQUEST',
        CONFIRMATION: true,
        BROKEN: false,
        FORMAT: [
            CHAT_PACKET_ATTRIBUTE.PACKET_TYPE,
            CHAT_PACKET_ATTRIBUTE.USER_ID,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID,
            CHAT_PACKET_ATTRIBUTE.START_INDEX,
            CHAT_PACKET_ATTRIBUTE.PAGE_LIMIT,
            CHAT_PACKET_ATTRIBUTE.PLATFORM,

        ],
    };

    // PACKET TYPE(1018) : PUBLIC_CHAT_ROOM_LIST_SEARCH_REQUEST
    PUBLIC_CHAT_PACKET_INFO[PUBLIC_CHAT_OFFLINE_PACKET_TYPE.PUBLIC_CHAT_ROOM_LIST_SEARCH_REQUEST] =
    {
        PACKET_NAME: 'PUBLIC_CHAT_ROOM_LIST_SEARCH_REQUEST',
        CONFIRMATION: true,
        BROKEN: false,
        FORMAT: [
            CHAT_PACKET_ATTRIBUTE.PACKET_TYPE,
            CHAT_PACKET_ATTRIBUTE.USER_ID,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID,
            CHAT_PACKET_ATTRIBUTE.START_INDEX,
            CHAT_PACKET_ATTRIBUTE.PAGE_LIMIT,
            CHAT_PACKET_ATTRIBUTE.SEARCH_NAME_LENGTH,
            CHAT_PACKET_ATTRIBUTE.SEARCH_NAME,
            CHAT_PACKET_ATTRIBUTE.COUNTRY_LENGTH,
            CHAT_PACKET_ATTRIBUTE.COUNTRY,
            CHAT_PACKET_ATTRIBUTE.CATEGORY_LENGTH,
            CHAT_PACKET_ATTRIBUTE.CATEGORY,
            CHAT_PACKET_ATTRIBUTE.PLATFORM,

        ],
    };

    // PACKET TYPE(1019) : PUBLIC_CHAT_ROOM_LIST_REQUEST_CONFIRMATION
    PUBLIC_CHAT_PACKET_INFO[PUBLIC_CHAT_OFFLINE_PACKET_TYPE.PUBLIC_CHAT_ROOM_LIST_REQUEST_CONFIRMATION] = {
        PACKET_NAME: 'PUBLIC_CHAT_ROOM_LIST_REQUEST_CONFIRMATION',
        CONFIRMATION: false,
        BROKEN: false,
        FORMAT: [
            CHAT_PACKET_ATTRIBUTE.PACKET_TYPE,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID,

        ],
    };

    // PACKET TYPE(1020) : PUBLIC_CHAT_ROOM_LIST
    PUBLIC_CHAT_PACKET_INFO[PUBLIC_CHAT_OFFLINE_PACKET_TYPE.PUBLIC_CHAT_ROOM_LIST] = {
        PACKET_NAME: 'PUBLIC_CHAT_ROOM_LIST',
        CONFIRMATION: false,
        BROKEN: true,
        FORMAT: [
            CHAT_PACKET_ATTRIBUTE.PACKET_TYPE,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID,
            CHAT_PACKET_ATTRIBUTE.NO_OF_ROOM, [
                CHAT_PACKET_ATTRIBUTE.ROOM_ID_LENGTH,
                CHAT_PACKET_ATTRIBUTE.ROOM_ID,
                CHAT_PACKET_ATTRIBUTE.ROOM_NAME_LENGTH,
                CHAT_PACKET_ATTRIBUTE.ROOM_NAME,
                CHAT_PACKET_ATTRIBUTE.ROOM_URL_LENGTH,
                CHAT_PACKET_ATTRIBUTE.ROOM_URL,

            ],

        ],
    };

    // PACKET TYPE(1021) : PUBLIC_CHAT_GET_ROOM_IPPORT
    PUBLIC_CHAT_PACKET_INFO[PUBLIC_CHAT_OFFLINE_PACKET_TYPE.PUBLIC_CHAT_GET_ROOM_IPPORT] = {
        PACKET_NAME: 'PUBLIC_CHAT_GET_ROOM_IPPORT',
        CONFIRMATION: true,
        BROKEN: false,
        FORMAT: [
            CHAT_PACKET_ATTRIBUTE.PACKET_TYPE,
            CHAT_PACKET_ATTRIBUTE.USER_ID,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID,
            CHAT_PACKET_ATTRIBUTE.PLATFORM,

        ],
    };

    // PACKET TYPE(1022) : PUBLIC_CHAT_ROOM_IPPORT_CONFIRMATION
    PUBLIC_CHAT_PACKET_INFO[PUBLIC_CHAT_OFFLINE_PACKET_TYPE.PUBLIC_CHAT_ROOM_IPPORT_CONFIRMATION] = {
        PACKET_NAME: 'PUBLIC_CHAT_ROOM_IPPORT_CONFIRMATION',
        CONFIRMATION: false,
        BROKEN: false,
        FORMAT: [
            CHAT_PACKET_ATTRIBUTE.PACKET_TYPE,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID,
            CHAT_PACKET_ATTRIBUTE.SERVER_IP_LENGTH,
            CHAT_PACKET_ATTRIBUTE.SERVER_IP,
            CHAT_PACKET_ATTRIBUTE.SERVER_REGISTER_PORT,
            CHAT_PACKET_ATTRIBUTE.NO_OF_MEMBER,

        ],
    };

    // PACKET TYPE(1023) : PUBLIC_CHAT_ROOM_INFORMATION_REQUEST
    PUBLIC_CHAT_PACKET_INFO[PUBLIC_CHAT_OFFLINE_PACKET_TYPE.PUBLIC_CHAT_ROOM_INFORMATION_REQUEST] = {
        PACKET_NAME: 'PUBLIC_CHAT_ROOM_INFORMATION_REQUEST',
        CONFIRMATION: true,
        BROKEN: false,
        FORMAT: [
            CHAT_PACKET_ATTRIBUTE.PACKET_TYPE,
            CHAT_PACKET_ATTRIBUTE.USER_ID,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID,
            CHAT_PACKET_ATTRIBUTE.PLATFORM,

        ],
    };

    // PACKET TYPE(1024) : PUBLIC_CHAT_ROOM_INFORMATION
    PUBLIC_CHAT_PACKET_INFO[PUBLIC_CHAT_OFFLINE_PACKET_TYPE.PUBLIC_CHAT_ROOM_INFORMATION] = {
        PACKET_NAME: 'PUBLIC_CHAT_ROOM_INFORMATION',
        CONFIRMATION: false,
        BROKEN: false,
        FORMAT: [
            CHAT_PACKET_ATTRIBUTE.PACKET_TYPE,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID,
            CHAT_PACKET_ATTRIBUTE.ROOM_NAME_LENGTH,
            CHAT_PACKET_ATTRIBUTE.ROOM_NAME,
            CHAT_PACKET_ATTRIBUTE.ROOM_URL_LENGTH,
            CHAT_PACKET_ATTRIBUTE.ROOM_URL,

        ],
    };

    // PACKET TYPE(1025) : PUBLIC_CHAT_GET_HISTORY
    PUBLIC_CHAT_PACKET_INFO[PUBLIC_CHAT_OFFLINE_PACKET_TYPE.PUBLIC_CHAT_GET_HISTORY] = {
        PACKET_NAME: 'PUBLIC_CHAT_GET_HISTORY',
        CONFIRMATION: true,
        BROKEN: false,
        FORMAT: [
            CHAT_PACKET_ATTRIBUTE.PACKET_TYPE,
            CHAT_PACKET_ATTRIBUTE.USER_ID,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID,
            CHAT_PACKET_ATTRIBUTE.MONTH,
            CHAT_PACKET_ATTRIBUTE.YEAR,
            CHAT_PACKET_ATTRIBUTE.PAGE_DIRECTION,
            CHAT_PACKET_ATTRIBUTE.PAGE_LIMIT,
            CHAT_PACKET_ATTRIBUTE.PLATFORM,
            CHAT_PACKET_ATTRIBUTE.APP_VERSION,

        ],
    };

    // PACKET TYPE(1026) : PUBLIC_CHAT_GET_HISTORY_CONFIRMATION
    PUBLIC_CHAT_PACKET_INFO[PUBLIC_CHAT_OFFLINE_PACKET_TYPE.PUBLIC_CHAT_GET_HISTORY_CONFIRMATION] = {
        PACKET_NAME: 'PUBLIC_CHAT_GET_HISTORY_CONFIRMATION',
        CONFIRMATION: false,
        BROKEN: false,
        FORMAT: [
            CHAT_PACKET_ATTRIBUTE.PACKET_TYPE,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID,

        ],
    };

    // PACKET TYPE(1027) : PUBLIC_CHAT_HISTORY_MESSAGE_LIST
    PUBLIC_CHAT_PACKET_INFO[PUBLIC_CHAT_OFFLINE_PACKET_TYPE.PUBLIC_CHAT_HISTORY_MESSAGE_LIST] =
    {
        PACKET_NAME: 'PUBLIC_CHAT_HISTORY_MESSAGE_LIST',
        CONFIRMATION: true,
        BROKEN: true,
        FORMAT: [
            CHAT_PACKET_ATTRIBUTE.PACKET_TYPE,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID,
            CHAT_PACKET_ATTRIBUTE.NO_OF_MESSAGE,
            [
                CHAT_PACKET_ATTRIBUTE.PACKET_TYPE,
                CHAT_PACKET_ATTRIBUTE.USER_ID,
                CHAT_PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
                CHAT_PACKET_ATTRIBUTE.PACKET_ID,
                CHAT_PACKET_ATTRIBUTE.MESSAGE_TYPE,
                CHAT_PACKET_ATTRIBUTE.MESSAGE_LENGTH,
                CHAT_PACKET_ATTRIBUTE.MESSAGE,
                CHAT_PACKET_ATTRIBUTE.MESSAGE_DATE,
                CHAT_PACKET_ATTRIBUTE.FULL_NAME_LENGTH,
                CHAT_PACKET_ATTRIBUTE.FULL_NAME,
                CHAT_PACKET_ATTRIBUTE.MEMBER_URL_LENGTH,
                CHAT_PACKET_ATTRIBUTE.MEMBER_URL,
                CHAT_PACKET_ATTRIBUTE.LIKE_COUNT,
                CHAT_PACKET_ATTRIBUTE.I_LIKE,
                CHAT_PACKET_ATTRIBUTE.I_REPORT,
            ],

        ],
    };

    // PACKET TYPE(1028) : PUBLIC_CHAT_ROOM_LIST_WITH_HISTORY_REQUEST
    PUBLIC_CHAT_PACKET_INFO[PUBLIC_CHAT_OFFLINE_PACKET_TYPE.PUBLIC_CHAT_ROOM_LIST_WITH_HISTORY_REQUEST] = {
        PACKET_NAME: 'PUBLIC_CHAT_ROOM_LIST_WITH_HISTORY_REQUEST',
        CONFIRMATION: true,
        BROKEN: false,
        FORMAT: [
            CHAT_PACKET_ATTRIBUTE.PACKET_TYPE,
            CHAT_PACKET_ATTRIBUTE.USER_ID,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID,
            CHAT_PACKET_ATTRIBUTE.START_INDEX,
            CHAT_PACKET_ATTRIBUTE.PAGE_LIMIT,
            CHAT_PACKET_ATTRIBUTE.PLATFORM,

        ],
    };

    // PACKET TYPE(1029) : PUBLIC_CHAT_ROOM_LIST_WITH_HISTORY
    PUBLIC_CHAT_PACKET_INFO[PUBLIC_CHAT_OFFLINE_PACKET_TYPE.PUBLIC_CHAT_ROOM_LIST_WITH_HISTORY] = {
        PACKET_NAME: 'PUBLIC_CHAT_ROOM_LIST_WITH_HISTORY',
        CONFIRMATION: true,
        BROKEN: true,
        FORMAT: [
            CHAT_PACKET_ATTRIBUTE.PACKET_TYPE,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID,
            CHAT_PACKET_ATTRIBUTE.NO_OF_ROOM, [
                CHAT_PACKET_ATTRIBUTE.ROOM_ID_LENGTH,
                CHAT_PACKET_ATTRIBUTE.ROOM_ID,
                CHAT_PACKET_ATTRIBUTE.ROOM_NAME_LENGTH,
                CHAT_PACKET_ATTRIBUTE.ROOM_NAME,
                CHAT_PACKET_ATTRIBUTE.ROOM_URL_LENGTH,
                CHAT_PACKET_ATTRIBUTE.ROOM_URL,
                CHAT_PACKET_ATTRIBUTE.NO_OF_MEMBER,
                CHAT_PACKET_ATTRIBUTE.NO_OF_MESSAGE, [
                    CHAT_PACKET_ATTRIBUTE.USER_ID,
                    CHAT_PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
                    CHAT_PACKET_ATTRIBUTE.PACKET_ID,
                    CHAT_PACKET_ATTRIBUTE.MESSAGE_TYPE,
                    CHAT_PACKET_ATTRIBUTE.MESSAGE_LENGTH,
                    CHAT_PACKET_ATTRIBUTE.MESSAGE,
                    CHAT_PACKET_ATTRIBUTE.MESSAGE_DATE,
                    CHAT_PACKET_ATTRIBUTE.FULL_NAME_LENGTH,
                    CHAT_PACKET_ATTRIBUTE.FULL_NAME,
                    CHAT_PACKET_ATTRIBUTE.MEMBER_URL_LENGTH,
                    CHAT_PACKET_ATTRIBUTE.MEMBER_URL,

                ],

            ],

        ],
    };

    // PACKET TYPE(1030) : PUBLIC_CHAT_BROKEN_PACKET
    PUBLIC_CHAT_PACKET_INFO[PUBLIC_CHAT_OFFLINE_PACKET_TYPE.PUBLIC_CHAT_BROKEN_PACKET] = {
        PACKET_NAME: 'PUBLIC_CHAT_BROKEN_PACKET',
        CONFIRMATION: true,
        BROKEN: false,
        FORMAT: [
            CHAT_PACKET_ATTRIBUTE.PACKET_TYPE,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID,
            CHAT_PACKET_ATTRIBUTE.NO_OF_PACKET,
            CHAT_PACKET_ATTRIBUTE.SEQUENCE_NO,
            CHAT_PACKET_ATTRIBUTE.RAW_DATA_BYTE,

        ],
    };

    // PACKET TYPE(1031) : PUBLIC_CHAT_BROKEN_CONFIRMATION
    PUBLIC_CHAT_PACKET_INFO[PUBLIC_CHAT_OFFLINE_PACKET_TYPE.PUBLIC_CHAT_BROKEN_CONFIRMATION] = {
        PACKET_NAME: 'PUBLIC_CHAT_BROKEN_CONFIRMATION',
        CONFIRMATION: false,
        BROKEN: false,
        FORMAT: [
            CHAT_PACKET_ATTRIBUTE.PACKET_TYPE,
            CHAT_PACKET_ATTRIBUTE.USER_ID,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID,
            CHAT_PACKET_ATTRIBUTE.SEQUENCE_NO,

        ],
    };

    // PACKET TYPE(1032) : PUBLIC_CHAT_SHADOW_IDS_INFO_REQUEST
    PUBLIC_CHAT_PACKET_INFO[PUBLIC_CHAT_OFFLINE_PACKET_TYPE.PUBLIC_CHAT_SHADOW_IDS_INFO_REQUEST] = {
        PACKET_NAME: 'PUBLIC_CHAT_SHADOW_IDS_INFO_REQUEST',
        CONFIRMATION: false,
        BROKEN: false,
        FORMAT: [
            CHAT_PACKET_ATTRIBUTE.PACKET_TYPE,
            CHAT_PACKET_ATTRIBUTE.USER_ID,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID,
            CHAT_PACKET_ATTRIBUTE.NO_OF_IDS, [
                CHAT_PACKET_ATTRIBUTE.USER_ID,

            ],
            CHAT_PACKET_ATTRIBUTE.PLATFORM,

        ],
    };

    // PACKET TYPE(1033) : PUBLIC_CHAT_SHADOW_IDS_INFO_RESPONSE
    PUBLIC_CHAT_PACKET_INFO[PUBLIC_CHAT_OFFLINE_PACKET_TYPE.PUBLIC_CHAT_SHADOW_IDS_INFO_RESPONSE] = {
        PACKET_NAME: 'PUBLIC_CHAT_SHADOW_IDS_INFO_RESPONSE',
        CONFIRMATION: false,
        BROKEN: true,
        FORMAT: [
            CHAT_PACKET_ATTRIBUTE.PACKET_TYPE,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID,
            CHAT_PACKET_ATTRIBUTE.NO_OF_IDS, [
                CHAT_PACKET_ATTRIBUTE.ROOM_ID_LENGTH,
                CHAT_PACKET_ATTRIBUTE.ROOM_ID,
                CHAT_PACKET_ATTRIBUTE.USER_ID,
                CHAT_PACKET_ATTRIBUTE.SHADOW_ID,
                CHAT_PACKET_ATTRIBUTE.FULL_NAME_LENGTH,
                CHAT_PACKET_ATTRIBUTE.FULL_NAME,
                CHAT_PACKET_ATTRIBUTE.MEMBER_URL_LENGTH,
                CHAT_PACKET_ATTRIBUTE.MEMBER_URL,

            ],

        ],
    };

    // PACKET TYPE(1034) : PUBLIC_CHAT_DELETE_MESSAGE
    PUBLIC_CHAT_PACKET_INFO[PUBLIC_CHAT_ONLINE_PACKET_TYPE.PUBLIC_CHAT_DELETE_MESSAGE] =
    {
        PACKET_NAME: 'PUBLIC_CHAT_DELETE_MESSAGE',
        CONFIRMATION: false,
        BROKEN: true,
        FORMAT: [
            CHAT_PACKET_ATTRIBUTE.PACKET_TYPE,
            CHAT_PACKET_ATTRIBUTE.USER_ID,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID,
            CHAT_PACKET_ATTRIBUTE.NO_OF_PACKET,
            [
                CHAT_PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
                CHAT_PACKET_ATTRIBUTE.PACKET_ID,

            ],

        ],
    };

      // PACKET TYPE(1035) : PUBLIC_CHAT_DELETE_MESSAGE_CONFIRMATION
    PUBLIC_CHAT_PACKET_INFO[PUBLIC_CHAT_ONLINE_PACKET_TYPE.PUBLIC_CHAT_DELETE_MESSAGE_CONFIRMATION] =
    {
        PACKET_NAME: 'PUBLIC_CHAT_DELETE_MESSAGE_CONFIRMATION',
        CONFIRMATION: false,
        BROKEN: false,
        FORMAT: [
            CHAT_PACKET_ATTRIBUTE.PACKET_TYPE,
            CHAT_PACKET_ATTRIBUTE.USER_ID,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID,

        ],
    };

      // PACKET TYPE(1036) : PUBLIC_CHAT_LIKE_A_MESSAGE
    PUBLIC_CHAT_PACKET_INFO[PUBLIC_CHAT_ONLINE_PACKET_TYPE.PUBLIC_CHAT_LIKE_A_MESSAGE] =
    {
        PACKET_NAME: 'PUBLIC_CHAT_LIKE_A_MESSAGE',
        CONFIRMATION: true,
        BROKEN: false,
        FORMAT: [
            CHAT_PACKET_ATTRIBUTE.PACKET_TYPE,
            CHAT_PACKET_ATTRIBUTE.USER_ID,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID,
            CHAT_PACKET_ATTRIBUTE.MESSENGER_OWNERID,
            CHAT_PACKET_ATTRIBUTE.ORIGINAL_PACKETID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.ORIGINAL_PACKETID,

        ],
    };

      // PACKET TYPE(1037) : PUBLIC_CHAT_UNLIKE_A_MESSAGE
    PUBLIC_CHAT_PACKET_INFO[PUBLIC_CHAT_ONLINE_PACKET_TYPE.PUBLIC_CHAT_UNLIKE_A_MESSAGE] =
    {
        PACKET_NAME: 'PUBLIC_CHAT_UNLIKE_A_MESSAGE',
        CONFIRMATION: true,
        BROKEN: false,
        FORMAT: [
            CHAT_PACKET_ATTRIBUTE.PACKET_TYPE,
            CHAT_PACKET_ATTRIBUTE.USER_ID,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID,
            CHAT_PACKET_ATTRIBUTE.MESSENGER_OWNERID,
            CHAT_PACKET_ATTRIBUTE.ORIGINAL_PACKETID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.ORIGINAL_PACKETID,

        ],
    };

      // PACKET TYPE(1038) : PUBLIC_CHAT_LIKE_UNLIKE_MESSAGE_CONFIRMATION
    PUBLIC_CHAT_PACKET_INFO[PUBLIC_CHAT_ONLINE_PACKET_TYPE.PUBLIC_CHAT_LIKE_UNLIKE_MESSAGE_CONFIRMATION] =
    {
        PACKET_NAME: 'PUBLIC_CHAT_LIKE_UNLIKE_MESSAGE_CONFIRMATION',
        CONFIRMATION: false,
        BROKEN: false,
        FORMAT: [
            CHAT_PACKET_ATTRIBUTE.PACKET_TYPE,
            CHAT_PACKET_ATTRIBUTE.USER_ID,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID,

        ],
    };

      // PACKET TYPE(1039) : PUBLIC_CHAT_REPORT_A_MESSAGE
    PUBLIC_CHAT_PACKET_INFO[PUBLIC_CHAT_ONLINE_PACKET_TYPE.PUBLIC_CHAT_REPORT_A_MESSAGE] =
    {
        PACKET_NAME: 'PUBLIC_CHAT_REPORT_A_MESSAGE',
        CONFIRMATION: true,
        BROKEN: false,
        FORMAT: [
            CHAT_PACKET_ATTRIBUTE.PACKET_TYPE,
            CHAT_PACKET_ATTRIBUTE.USER_ID,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID,
            CHAT_PACKET_ATTRIBUTE.MESSENGER_OWNERID,
            CHAT_PACKET_ATTRIBUTE.ORIGINAL_PACKETID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.ORIGINAL_PACKETID,
            CHAT_PACKET_ATTRIBUTE.REPORT_MESSAGE_LENGTH,
            CHAT_PACKET_ATTRIBUTE.REPORT_MESSAGE,

        ],
    };

    // PACKET TYPE(1040) : PUBLIC_CHAT_REPORT_A_MESSAGE_CONFIRMATION
    PUBLIC_CHAT_PACKET_INFO[PUBLIC_CHAT_ONLINE_PACKET_TYPE.PUBLIC_CHAT_REPORT_A_MESSAGE_CONFIRMATION] =
    {
        PACKET_NAME: 'PUBLIC_CHAT_REPORT_A_MESSAGE_CONFIRMATION',
        CONFIRMATION: false,
        BROKEN: false,
        FORMAT: [
            CHAT_PACKET_ATTRIBUTE.PACKET_TYPE,
            CHAT_PACKET_ATTRIBUTE.USER_ID,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID,

        ],
    };

      // PACKET TYPE(1041) : PUBLIC_CHAT_LIKE_MEMBER_LIST_REQUEST
    PUBLIC_CHAT_PACKET_INFO[PUBLIC_CHAT_ONLINE_PACKET_TYPE.PUBLIC_CHAT_LIKE_MEMBER_LIST_REQUEST] =
    {
        PACKET_NAME: 'PUBLIC_CHAT_LIKE_MEMBER_LIST_REQUEST',
        CONFIRMATION: true,
        BROKEN: false,
        FORMAT: [
            CHAT_PACKET_ATTRIBUTE.PACKET_TYPE,
            CHAT_PACKET_ATTRIBUTE.USER_ID,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID,
            CHAT_PACKET_ATTRIBUTE.ORIGINAL_PACKETID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.ORIGINAL_PACKETID,
            CHAT_PACKET_ATTRIBUTE.PUBLIC_CHAT_LAST_LIKER_ID,
            CHAT_PACKET_ATTRIBUTE.PAGE_LIMIT,

        ],
    };

      // PACKET TYPE(1042) : PUBLIC_CHAT_LIKE_MEMBER_LIST
    PUBLIC_CHAT_PACKET_INFO[PUBLIC_CHAT_ONLINE_PACKET_TYPE.PUBLIC_CHAT_LIKE_MEMBER_LIST] =
    {
        PACKET_NAME: 'PUBLIC_CHAT_LIKE_MEMBER_LIST',
        CONFIRMATION: true,
        BROKEN: false,
        FORMAT: [
            CHAT_PACKET_ATTRIBUTE.PACKET_TYPE,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.ROOM_ID,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID,
            CHAT_PACKET_ATTRIBUTE.TOTAL_ITEMS,
            [
                CHAT_PACKET_ATTRIBUTE.USER_ID,
                CHAT_PACKET_ATTRIBUTE.FULL_NAME_LENGTH,
                CHAT_PACKET_ATTRIBUTE.FULL_NAME,
                CHAT_PACKET_ATTRIBUTE.MEMBER_URL_LENGTH,
                CHAT_PACKET_ATTRIBUTE.MEMBER_URL,

            ],

        ],
    };

      // PACKET TYPE(1043) : PUBLIC_CHAT_CATEGORY_LIST_REQUEST
    PUBLIC_CHAT_PACKET_INFO[PUBLIC_CHAT_ONLINE_PACKET_TYPE.PUBLIC_CHAT_CATEGORY_LIST_REQUEST] =
    {
        PACKET_NAME: 'PUBLIC_CHAT_CATEGORY_LIST_REQUEST',
        CONFIRMATION: true,
        BROKEN: false,
        FORMAT: [
            CHAT_PACKET_ATTRIBUTE.PACKET_TYPE,
            CHAT_PACKET_ATTRIBUTE.USER_ID,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID,
            CHAT_PACKET_ATTRIBUTE.LAST_CATEGORY_LENGTH,
            CHAT_PACKET_ATTRIBUTE.LAST_CATEGORY,
            CHAT_PACKET_ATTRIBUTE.PAGE_LIMIT,
            CHAT_PACKET_ATTRIBUTE.PLATFORM,

        ],
    };

      // PACKET TYPE(1044) : PUBLIC_CHAT_CATEGORY_LIST
    PUBLIC_CHAT_PACKET_INFO[PUBLIC_CHAT_ONLINE_PACKET_TYPE.PUBLIC_CHAT_CATEGORY_LIST] =
    {
        PACKET_NAME: 'PUBLIC_CHAT_CATEGORY_LIST',
        CONFIRMATION: false,
        BROKEN: false,
        FORMAT: [
            CHAT_PACKET_ATTRIBUTE.PACKET_TYPE,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID_LENGTH,
            CHAT_PACKET_ATTRIBUTE.PACKET_ID,
            CHAT_PACKET_ATTRIBUTE.TOTAL_ITEMS,
            [
                CHAT_PACKET_ATTRIBUTE.CATEGORY_LENGTH,
                CHAT_PACKET_ATTRIBUTE.CATEGORY,

            ],

        ],
    };


    global.CHAT_APP.PacketFormats.PUBLIC_CHAT_PACKET_INFO = PUBLIC_CHAT_PACKET_INFO;
})(window);
